// Cloudflare Pages Function: POST /api/pulse
//
// Feeds the two live numbers in the stats strip on the home page: how many
// distinct people visited in the last 30 days, and how many are reading right
// now. Every page on the site calls this on load and then every 30 seconds
// while its tab is visible; only the home page draws the result.
//
// One request does the whole job — record, sweep, and read both counts — in a
// single D1 batch, which runs as one transaction and one round trip.
//
// The same response also carries the two personal corners: the last public
// place I was seen at (written by /api/where) and what I'm listening to on
// Spotify (cached here, refreshed off the request path — see the Spotify
// section below).
//
// Required bindings (wrangler.toml / Pages dashboard):
//   PULSE_DB    D1 database, schema in schema.sql at the repo root
//   PULSE_SALT  random string, secret. See the note on hashing below.
//   SPOTIFY_CLIENT_ID / SPOTIFY_CLIENT_SECRET
//               optional; without them the music corner just stays empty.

const WINDOW_DAYS = 30;      // the "(30d)" in the label
const TRACK_TTL = 25;        // seconds the cached Spotify track is served as-is
const RETAIN_DAYS = 60;      // how long day-rows are kept before being swept
const ONLINE_SECONDS = 70;   // a tab counts as online this long after a beat
const PRESENCE_TTL = 600;    // and its row is deleted this long after one
const MAX_FLAGS = 10;        // distinct countries returned; see countryOf below
const PLACE_TTL = 259200;    // 3 days; after that the corner says nothing at all

// The client beats every 30s, so 70 tolerates exactly one dropped beat before
// someone blinks out — a laptop lid closing shouldn't take two minutes to
// register, and a flaky connection shouldn't make the number flicker.

// Tab ids are generated by crypto.randomUUID(); anything else is someone
// typing into the endpoint by hand, and each novel id would otherwise be a
// free +1 to the online count.
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export async function onRequestPost({ request, env, waitUntil }) {
  try {
    // Same-origin only, as with /api/detect: this writes to the database, and
    // there's no reason for anything but this site's own pages to call it.
    const origin = request.headers.get("Origin");
    if (origin && new URL(origin).hostname !== new URL(request.url).hostname) {
      return json({ error: "Forbidden" }, 403);
    }

    const db = env.PULSE_DB;
    if (!db) return json({ error: "PULSE_DB is not bound" }, 500);

    let body = {};
    try {
      body = await request.json();
    } catch (e) {
      /* an empty beat is still a valid beat; fall through with no tab */
    }

    const tab = typeof body.tab === "string" && UUID.test(body.tab) ? body.tab : null;
    // The client sets this on the first beat of a browsing session. It isn't
    // trusted for correctness — the (day, visitor) primary key is what makes
    // the count unique — it just keeps every heartbeat from attempting a write
    // that the database would throw away anyway.
    const fresh = body.fresh === true && !isBot(request);

    const today = utcDay(0);
    const since = utcDay(-(WINDOW_DAYS - 1));  // inclusive, so today + 29 back
    const expiry = utcDay(-RETAIN_DAYS);

    const stmts = [];

    if (fresh) {
      stmts.push(
        db.prepare("INSERT OR IGNORE INTO hits (day, visitor) VALUES (?1, ?2)")
          .bind(today, await visitorHash(request, env, today)),
        // Cheap: the primary key is (day, visitor), so this is a range scan
        // over the oldest edge of the index, and on most days it matches
        // nothing at all.
        db.prepare("DELETE FROM hits WHERE day < ?1").bind(expiry),
      );
    }

    if (tab) {
      stmts.push(
        db.prepare(
          `INSERT INTO presence (tab, seen, country) VALUES (?1, unixepoch(), ?2)
             ON CONFLICT(tab) DO UPDATE SET seen = excluded.seen,
                                            country = excluded.country`,
        ).bind(tab, countryOf(request)),
        db.prepare("DELETE FROM presence WHERE seen < unixepoch() - ?1")
          .bind(PRESENCE_TTL),
      );
    }

    // The reads go last, so they see this request's own writes. Their
    // positions are recorded rather than counted back from the end of the
    // batch: which writes ran depends on the request, and counting backwards
    // would eventually read a DELETE's result as a count.
    const at = {};
    at.visits = stmts.push(
      db.prepare("SELECT COUNT(*) AS n FROM hits WHERE day >= ?1").bind(since),
    ) - 1;
    at.online = stmts.push(
      db.prepare("SELECT COUNT(*) AS n FROM presence WHERE seen > unixepoch() - ?1")
        .bind(ONLINE_SECONDS),
    ) - 1;
    // DISTINCT is the whole feature: three tabs open in one country are one
    // flag, three countries are three. Ordered so the row doesn't reshuffle
    // itself between heartbeats.
    at.countries = stmts.push(
      db.prepare(
        `SELECT DISTINCT country FROM presence
          WHERE seen > unixepoch() - ?1 AND country IS NOT NULL
          ORDER BY country
          LIMIT ?2`,
      ).bind(ONLINE_SECONDS, MAX_FLAGS),
    ) - 1;
    // The place in the other corner, written by /api/where. It rides along on
    // this batch rather than getting an endpoint of its own: every page is
    // already beating here every 30s, so the widget costs one statement on a
    // query that was happening anyway instead of a second request per tab.
    //
    // The cutoff is enforced here rather than in the browser so a stale row
    // never leaves the database at all. Three days lets "2 days ago" ride
    // out a quiet weekend; past that the corner goes silent rather than
    // becoming a monument to the last time I left the house.
    at.place = stmts.push(
      db.prepare(
        `SELECT label, city, area, unixepoch() - seen AS ago FROM place
          WHERE id = 1 AND seen > unixepoch() - ?1`,
      ).bind(PLACE_TTL),
    ) - 1;
    // The music line in the third corner. Same deal as place: it rides the
    // batch that was happening anyway. Only the cache is read here — Spotify
    // itself is never on this request's critical path (see refreshSpotify).
    at.spotify = stmts.push(
      db.prepare(
        `SELECT refresh_token, access_token, token_expires, track,
                unixepoch() - COALESCE(fetched, 0) AS age
           FROM spotify WHERE id = 1`,
      ),
    ) - 1;

    const results = await db.batch(stmts);
    const visits = count(results[at.visits]);
    // A tab that sent no id isn't in the table but is plainly here, so it
    // counts itself rather than reading "0 online" to the one person online.
    const online = Math.max(count(results[at.online]), 1);
    const countries = (results[at.countries]?.results || [])
      .map((row) => row.country)
      .filter(Boolean);
    const row = results[at.place]?.results?.[0];
    // Age in seconds rather than a timestamp, so the browser has nothing to
    // reconcile against its own clock and no date to mis-parse — and so the
    // wording around it stays a rendering decision.
    const place = row
      ? { label: row.label, city: row.city || null, area: row.area || null,
          ago: Math.max(row.ago, 0) }
      : null;

    // The cached track goes out as-is — even when stale, because a song from
    // a minute ago beats a corner that flickers empty. If it's older than one
    // beat, a refresh runs after this response is already on the wire;
    // whoever asks next gets the new one. Serving stale-while-revalidating
    // keeps Spotify's latency (and its bad days) off every reader's request.
    const spot = results[at.spotify]?.results?.[0];
    let track = null;
    if (spot) {
      try {
        track = JSON.parse(spot.track);
      } catch (e) {
        /* an unseeded or corrupt cache is just "no track yet" */
      }
      if (track) {
        // As with place: an age in seconds rather than a timestamp, computed
        // here so the browser has nothing to reconcile against its own clock.
        // The cached blob stores when the track finished (`at`, absent while
        // one is playing); the wire carries only the distance from now.
        track.ago = track.at ? Math.max(Math.floor(Date.now() / 1000) - track.at, 0) : null;
        delete track.at;
        delete track.seen;
        delete track.ends;
      }
      if (spot.age > TRACK_TTL) waitUntil(refreshSpotify(db, env, spot));
    }

    return json({ visits, online, countries, place, track }, 200);
  } catch (error) {
    console.error("Pulse Error:", error);
    return json({ error: "Internal Server Error" }, 500);
  }
}

// ---- Spotify --------------------------------------------------------------
//
// Refresh the cached track, off the request path (this runs via waitUntil,
// after the response has gone out). One Spotify round trip per TTL window
// regardless of how many tabs are beating — the cache row in D1 is what every
// request actually reads.
//
// Required for this to do anything (dashboard / .dev.vars):
//   SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET
// plus a refresh token seeded into the spotify table by tools/spotify/.
//
// Access tokens last an hour and are minted here from the refresh token when
// the cached one is within a minute of expiring. Spotify may rotate the
// refresh token itself on any mint (this app's tokens expire 180 days after
// issue), which is why the token lives in D1 and is written back on every
// change — a rotated token that wasn't persisted would kill the connection
// the next time this cold-started.
const SPOTIFY_MS = 6000;   // per-call budget; we're off the request path, but
                           // waitUntil still shouldn't hang for minutes

// Exported for /api/spotify-poll, the scheduled beat that keeps podcast
// episodes observable when nobody happens to be visiting the site.
export async function refreshSpotify(db, env, row) {
  try {
    if (!env.SPOTIFY_CLIENT_ID || !env.SPOTIFY_CLIENT_SECRET) return;

    let { refresh_token, access_token, token_expires } = row;
    const now = Math.floor(Date.now() / 1000);

    if (!access_token || !token_expires || token_expires - 60 < now) {
      const res = await fetch("https://accounts.spotify.com/api/token", {
        method: "POST",
        headers: {
          Authorization:
            "Basic " + btoa(`${env.SPOTIFY_CLIENT_ID}:${env.SPOTIFY_CLIENT_SECRET}`),
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({ grant_type: "refresh_token", refresh_token }),
        signal: AbortSignal.timeout(SPOTIFY_MS),
      });
      if (!res.ok) {
        // 400 invalid_grant here means the refresh token is dead (expired or
        // revoked) and the fix is re-running the authorize script; anything
        // else is Spotify having a moment and the next beat retries.
        console.warn(`spotify token mint failed: ${res.status}`);
        return;
      }
      const t = await res.json();
      access_token = t.access_token;
      token_expires = now + (t.expires_in || 3600);
      if (t.refresh_token) refresh_token = t.refresh_token;
    }

    // What's playing right now; failing that, the last thing that played.
    // 204 means nothing is playing. Podcasts count — an episode shows with
    // its show's name where the artist would go.
    //
    // Spotify's history endpoint doesn't record episodes, so a finished
    // podcast leaves no trace we can query — the only durable record is our
    // own: every pass that sees something live stamps the blob with `seen`.
    // When playback stops, that last observation becomes the item's stand-in
    // finish time and competes with the history endpoint's last song;
    // whichever is newer wins. The stamp is only as fresh as the last beat
    // that saw the episode playing, so a podcast heard with no tab open
    // anywhere still falls back to the last song — that's the ceiling of
    // what the API allows.
    let track = await nowPlaying(access_token);
    if (track) {
      track.seen = now;
      // Where the episode is heading, not just that we saw it. Spotify hands
      // back how far in we are and how long the item runs, so one look
      // anywhere inside a 90-minute episode already knows when it ends —
      // see `remembered` for why that's worth storing.
      if (track.remaining != null) track.ends = now + track.remaining;
      delete track.remaining;
    } else {
      // History first, so `remembered` can be told what played after us. A
      // song that started while we thought the episode was still running is
      // the only evidence available that it was cut short.
      const history = await lastPlayed(access_token);
      track = latest(remembered(row.track, now, history?.at ?? null), history);
    }

    // COALESCE keeps the previous track when this pass produced nothing (a
    // flaked API call, or a brand-new account with no history) — the corner
    // holds its last answer rather than blinking out. fetched advances either
    // way, so a bad Spotify afternoon costs one background call per TTL, not
    // one per heartbeat.
    await db
      .prepare(
        `UPDATE spotify
            SET refresh_token = ?1, access_token = ?2, token_expires = ?3,
                track = COALESCE(?4, track), fetched = unixepoch()
          WHERE id = 1`,
      )
      .bind(refresh_token, access_token, token_expires,
            track ? JSON.stringify(track) : null)
      .run();
  } catch (error) {
    // Never let the music corner take the counters down with it.
    console.warn("spotify refresh failed:", error);
  }
}

async function nowPlaying(token) {
  // Without additional_types the endpoint answers a playing podcast with
  // currently_playing_type: "episode" and item: null — it looks exactly like
  // a parse failure and cost a real debugging session. Asking for episodes
  // is what makes them exist at all.
  const res = await fetch(
    "https://api.spotify.com/v1/me/player/currently-playing?additional_types=episode",
    { headers: { Authorization: `Bearer ${token}` },
      signal: AbortSignal.timeout(SPOTIFY_MS) },
  ).catch(() => null);
  if (!res || res.status !== 200) return null;
  const data = await res.json().catch(() => null);
  if (!data?.item) return null;
  const track = shape(data.item, data.is_playing === true);
  // How much of this item is left, in seconds. Only meaningful while it's
  // actually playing — a paused item's progress stops predicting anything.
  const left = (data.item.duration_ms - data.progress_ms) / 1000;
  if (data.is_playing === true && Number.isFinite(left) && left >= 0) {
    track.remaining = Math.round(left);
  }
  return track;
}

async function lastPlayed(token) {
  const res = await fetch(
    "https://api.spotify.com/v1/me/player/recently-played?limit=1",
    { headers: { Authorization: `Bearer ${token}` },
      signal: AbortSignal.timeout(SPOTIFY_MS) },
  ).catch(() => null);
  if (!res || !res.ok) return null;
  const data = await res.json().catch(() => null);
  const entry = data?.items?.[0];
  if (!entry?.track) return null;
  const at = Math.floor(Date.parse(entry.played_at) / 1000);
  return shape(entry.track, false, Number.isFinite(at) ? at : null);
}

// The previous cache entry, recast as a finished item so it can be ranked
// against the history endpoint's answer. A blob carrying `seen` was live the
// last time we looked; a blob already carrying `at` finished long ago and
// ranks as-is. A blob with neither has no place on a timeline (a pre-`seen`
// cache, or corrupt) and is dropped rather than guessed at.
//
// Working out when a `seen` blob finished is the whole reason `ends` exists.
// The last look is a lower bound and nothing more: a podcast observed five
// minutes into an hour and never seen again really did end fifty-five
// minutes later, and stamping it at the observation ages it by an hour it
// never sat idle. Three facts narrow it down:
//
//   ends       where playback was heading when we last looked
//   now        the moment we found it stopped
//   historyAt  when the next song started, if one did
//
// If it had time to reach `ends` before we noticed the silence, it ran to
// completion and `ends` is exact — which is what decouples the corner's
// accuracy from how often the poll fires. If we caught the stop early, it
// was cut short somewhere between the last look and now, and the last look
// is the only instant anyone can actually attest to, so nothing is invented.
// Either way a song that started after the last look proves playback had
// already moved on by then, and caps the answer: an episode cannot still be
// running through a song.
function remembered(blob, now, historyAt = null) {
  let prev = null;
  try {
    prev = JSON.parse(blob);
  } catch (e) {
    return null;
  }
  if (prev?.seen) {
    let at = prev.seen;
    if (prev.ends && now >= prev.ends) at = prev.ends;
    if (historyAt && historyAt > prev.seen) at = Math.min(at, historyAt);
    return { title: prev.title, artist: prev.artist, playing: false, at };
  }
  return prev?.at ? prev : null;
}

// Whichever finished more recently. Ties (and anything unrankable) go to the
// history entry — its played_at is Spotify's clock, not our beat cadence.
function latest(a, b) {
  if (!a) return b;
  if (!b) return a;
  return (a.at || 0) > (b.at || 0) ? a : b;
}

// The cached blob: a title, who made it, whether it's live right now, and —
// for a finished track — when it finished, which the response handler above
// converts to a coarse age for the hover hint. A live one also carries `seen`
// and `ends`, both of which exist only to work out that finish time later and
// are stripped before the wire. No link, no album art, no progress bar: the
// corner is one line of plain text, and where playback has got to is working
// state, not something a reader is shown. For a podcast episode the show's
// name stands where the artists would — that's the name a reader recognizes.
function shape(item, playing, at = null) {
  const artist = item.artists?.length
    ? item.artists.map((a) => a.name).join(", ")
    : item.show?.name || "";
  return {
    title: item.name,
    artist,
    playing,
    ...(at ? { at } : {}),
  };
}

// The stable-per-day identity behind the unique-visitor count.
//
// Salting matters more than it looks like it should. IPv4 is only ~4 billion
// values, so an unsalted hash of an address is not an anonymization at all —
// anyone holding the table could enumerate the whole space in minutes and
// recover every visitor's IP. With a secret salt they can't, and rolling the
// day into the input means the table can't be used to follow one person from
// one day to the next either.
async function visitorHash(request, env, day) {
  const ip = request.headers.get("CF-Connecting-IP") || "";
  // A missing salt would silently turn the above into the enumerable case, so
  // it's loud. The fallback keeps the widget alive rather than 500ing the
  // page, but the counts it produces should be treated as compromised.
  const salt = env.PULSE_SALT;
  if (!salt) console.error("PULSE_SALT is not set — visitor hashes are guessable");

  const input = new TextEncoder().encode(`${salt || "unsalted"}:${day}:${ip}`);
  const digest = await crypto.subtle.digest("SHA-256", input);
  // 80 bits is far past what a personal site's traffic could collide on, and
  // keeps the rows small.
  return [...new Uint8Array(digest).slice(0, 10)]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// Cloudflare tags every request with the country it entered the network from,
// which is the one thing the flags need and the only thing about a visitor
// this endpoint stores. A few of the codes it can return aren't countries: XX
// when it couldn't tell, T1 for Tor exit nodes, and the regional stand-ins AP
// and EU. None of them have a flag — the regional-indicator pair for "XX"
// renders as two boxed letters — so they're dropped and that visitor is
// counted in the number without appearing in the row.
const NOT_A_COUNTRY = new Set(["XX", "T1", "AP", "EU"]);

function countryOf(request) {
  const cc = (request.cf?.country || request.headers.get("CF-IPCountry") || "")
    .toUpperCase();
  if (!/^[A-Z]{2}$/.test(cc) || NOT_A_COUNTRY.has(cc)) return null;
  return cc;
}

// Crawlers that execute JavaScript would otherwise land in the visitor count.
// This only gates counting — bots still get the numbers back, they just don't
// become one.
function isBot(request) {
  const ua = (request.headers.get("User-Agent") || "").toLowerCase();
  if (!ua) return true;
  return /bot|crawl|spider|slurp|headless|preview|lighthouse|monitor|curl|wget|python-|node-fetch|axios/.test(ua);
}

// 'YYYY-MM-DD' in UTC, offset by a number of days. UTC rather than local time
// so the day boundary is the same one the database rows were written against,
// wherever the request was served from.
function utcDay(offset) {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() + offset);
  return d.toISOString().slice(0, 10);
}

function count(result) {
  return result?.results?.[0]?.n ?? 0;
}

function json(body, status) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json",
      // These change every few seconds and are per-visitor on the write side;
      // nothing in the chain should be holding a copy.
      "Cache-Control": "no-store",
    },
  });
}
