// Cloudflare Pages Function: POST /api/pulse
//
// Feeds the two live numbers in the stats strip on the home page: how many
// distinct people visited in the last 30 days, and how many are reading right
// now. Every page on the site calls this on load and then every 30 seconds
// while its tab is visible; only the home page draws the result.
//
// One request does the whole job — record, sweep, and read both counts — in a
// single D1 batch, which runs as one transaction and one round trip.
//
// Required bindings (wrangler.toml / Pages dashboard):
//   PULSE_DB    D1 database, schema in schema.sql at the repo root
//   PULSE_SALT  random string, secret. See the note on hashing below.

const WINDOW_DAYS = 30;      // the "(30d)" in the label
const RETAIN_DAYS = 60;      // how long day-rows are kept before being swept
const ONLINE_SECONDS = 70;   // a tab counts as online this long after a beat
const PRESENCE_TTL = 600;    // and its row is deleted this long after one
const MAX_FLAGS = 10;        // distinct countries returned; see countryOf below
const PLACE_TTL = 259200;    // 3 days; after that the corner says nothing at all

// The client beats every 30s, so 70 tolerates exactly one dropped beat before
// someone blinks out — a laptop lid closing shouldn't take two minutes to
// register, and a flaky connection shouldn't make the number flicker.

// Tab ids are generated by crypto.randomUUID(); anything else is someone
// typing into the endpoint by hand, and each novel id would otherwise be a
// free +1 to the online count.
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export async function onRequestPost({ request, env }) {
  try {
    // Same-origin only, as with /api/detect: this writes to the database, and
    // there's no reason for anything but this site's own pages to call it.
    const origin = request.headers.get("Origin");
    if (origin && new URL(origin).hostname !== new URL(request.url).hostname) {
      return json({ error: "Forbidden" }, 403);
    }

    const db = env.PULSE_DB;
    if (!db) return json({ error: "PULSE_DB is not bound" }, 500);

    let body = {};
    try {
      body = await request.json();
    } catch (e) {
      /* an empty beat is still a valid beat; fall through with no tab */
    }

    const tab = typeof body.tab === "string" && UUID.test(body.tab) ? body.tab : null;
    // The client sets this on the first beat of a browsing session. It isn't
    // trusted for correctness — the (day, visitor) primary key is what makes
    // the count unique — it just keeps every heartbeat from attempting a write
    // that the database would throw away anyway.
    const fresh = body.fresh === true && !isBot(request);

    const today = utcDay(0);
    const since = utcDay(-(WINDOW_DAYS - 1));  // inclusive, so today + 29 back
    const expiry = utcDay(-RETAIN_DAYS);

    const stmts = [];

    if (fresh) {
      stmts.push(
        db.prepare("INSERT OR IGNORE INTO hits (day, visitor) VALUES (?1, ?2)")
          .bind(today, await visitorHash(request, env, today)),
        // Cheap: the primary key is (day, visitor), so this is a range scan
        // over the oldest edge of the index, and on most days it matches
        // nothing at all.
        db.prepare("DELETE FROM hits WHERE day < ?1").bind(expiry),
      );
    }

    if (tab) {
      stmts.push(
        db.prepare(
          `INSERT INTO presence (tab, seen, country) VALUES (?1, unixepoch(), ?2)
             ON CONFLICT(tab) DO UPDATE SET seen = excluded.seen,
                                            country = excluded.country`,
        ).bind(tab, countryOf(request)),
        db.prepare("DELETE FROM presence WHERE seen < unixepoch() - ?1")
          .bind(PRESENCE_TTL),
      );
    }

    // The reads go last, so they see this request's own writes. Their
    // positions are recorded rather than counted back from the end of the
    // batch: which writes ran depends on the request, and counting backwards
    // would eventually read a DELETE's result as a count.
    const at = {};
    at.visits = stmts.push(
      db.prepare("SELECT COUNT(*) AS n FROM hits WHERE day >= ?1").bind(since),
    ) - 1;
    at.online = stmts.push(
      db.prepare("SELECT COUNT(*) AS n FROM presence WHERE seen > unixepoch() - ?1")
        .bind(ONLINE_SECONDS),
    ) - 1;
    // DISTINCT is the whole feature: three tabs open in one country are one
    // flag, three countries are three. Ordered so the row doesn't reshuffle
    // itself between heartbeats.
    at.countries = stmts.push(
      db.prepare(
        `SELECT DISTINCT country FROM presence
          WHERE seen > unixepoch() - ?1 AND country IS NOT NULL
          ORDER BY country
          LIMIT ?2`,
      ).bind(ONLINE_SECONDS, MAX_FLAGS),
    ) - 1;
    // The place in the other corner, written by /api/where. It rides along on
    // this batch rather than getting an endpoint of its own: every page is
    // already beating here every 30s, so the widget costs one statement on a
    // query that was happening anyway instead of a second request per tab.
    //
    // The cutoff is enforced here rather than in the browser so a stale row
    // never leaves the database at all. Three days lets "2 days ago" ride
    // out a quiet weekend; past that the corner goes silent rather than
    // becoming a monument to the last time I left the house.
    at.place = stmts.push(
      db.prepare(
        `SELECT label, city, unixepoch() - seen AS ago FROM place
          WHERE id = 1 AND seen > unixepoch() - ?1`,
      ).bind(PLACE_TTL),
    ) - 1;

    const results = await db.batch(stmts);
    const visits = count(results[at.visits]);
    // A tab that sent no id isn't in the table but is plainly here, so it
    // counts itself rather than reading "0 online" to the one person online.
    const online = Math.max(count(results[at.online]), 1);
    const countries = (results[at.countries]?.results || [])
      .map((row) => row.country)
      .filter(Boolean);
    const row = results[at.place]?.results?.[0];
    // Age in seconds rather than a timestamp, so the browser has nothing to
    // reconcile against its own clock and no date to mis-parse — and so the
    // wording around it stays a rendering decision.
    const place = row
      ? { label: row.label, city: row.city || null, ago: Math.max(row.ago, 0) }
      : null;

    return json({ visits, online, countries, place }, 200);
  } catch (error) {
    console.error("Pulse Error:", error);
    return json({ error: "Internal Server Error" }, 500);
  }
}

// The stable-per-day identity behind the unique-visitor count.
//
// Salting matters more than it looks like it should. IPv4 is only ~4 billion
// values, so an unsalted hash of an address is not an anonymization at all —
// anyone holding the table could enumerate the whole space in minutes and
// recover every visitor's IP. With a secret salt they can't, and rolling the
// day into the input means the table can't be used to follow one person from
// one day to the next either.
async function visitorHash(request, env, day) {
  const ip = request.headers.get("CF-Connecting-IP") || "";
  // A missing salt would silently turn the above into the enumerable case, so
  // it's loud. The fallback keeps the widget alive rather than 500ing the
  // page, but the counts it produces should be treated as compromised.
  const salt = env.PULSE_SALT;
  if (!salt) console.error("PULSE_SALT is not set — visitor hashes are guessable");

  const input = new TextEncoder().encode(`${salt || "unsalted"}:${day}:${ip}`);
  const digest = await crypto.subtle.digest("SHA-256", input);
  // 80 bits is far past what a personal site's traffic could collide on, and
  // keeps the rows small.
  return [...new Uint8Array(digest).slice(0, 10)]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// Cloudflare tags every request with the country it entered the network from,
// which is the one thing the flags need and the only thing about a visitor
// this endpoint stores. A few of the codes it can return aren't countries: XX
// when it couldn't tell, T1 for Tor exit nodes, and the regional stand-ins AP
// and EU. None of them have a flag — the regional-indicator pair for "XX"
// renders as two boxed letters — so they're dropped and that visitor is
// counted in the number without appearing in the row.
const NOT_A_COUNTRY = new Set(["XX", "T1", "AP", "EU"]);

function countryOf(request) {
  const cc = (request.cf?.country || request.headers.get("CF-IPCountry") || "")
    .toUpperCase();
  if (!/^[A-Z]{2}$/.test(cc) || NOT_A_COUNTRY.has(cc)) return null;
  return cc;
}

// Crawlers that execute JavaScript would otherwise land in the visitor count.
// This only gates counting — bots still get the numbers back, they just don't
// become one.
function isBot(request) {
  const ua = (request.headers.get("User-Agent") || "").toLowerCase();
  if (!ua) return true;
  return /bot|crawl|spider|slurp|headless|preview|lighthouse|monitor|curl|wget|python-|node-fetch|axios/.test(ua);
}

// 'YYYY-MM-DD' in UTC, offset by a number of days. UTC rather than local time
// so the day boundary is the same one the database rows were written against,
// wherever the request was served from.
function utcDay(offset) {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() + offset);
  return d.toISOString().slice(0, 10);
}

function count(result) {
  return result?.results?.[0]?.n ?? 0;
}

function json(body, status) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json",
      // These change every few seconds and are per-visitor on the write side;
      // nothing in the chain should be holding a copy.
      "Cache-Control": "no-store",
    },
  });
}
