/* Generated by make-data.py — do not edit by hand. */
window.__UNPAK_DEMO__ = {
 "customer": "Calloway Freight",
 "window": {
  "start": "2026-05-12",
  "through": "2026-07-09",
  "days": 42
 },
 "kpis": {
  "people": 29,
  "runs": 2779,
  "aiRuns": 246,
  "aiSharePct": 9,
  "workflows": 32,
  "hoursObserved": 2707,
  "devicesActive": 31,
  "devicesTotal": 34,
  "moments": 704318
 },
 "teams": [
  {
   "name": "All employees",
   "people": 29
  }
 ],
 "feed": {
  "day": "2026-07-09",
  "items": [
   {
    "cat": "Most active workflow",
    "dot": "good",
    "goto": "workflows",
    "wf": "track-and-trace",
    "html": "<b>Load track-and-trace and status updates</b> \u00b7 19 runs by 8 people \u00b7 above its usual 9 to 15 a day"
   },
   {
    "cat": "New procedures",
    "dot": "good",
    "goto": "workflows",
    "wf": "fuel-surcharge",
    "html": "New procedure mapped: <b>Weekly fuel surcharge update</b> \u00b7 6 runs"
   },
   {
    "cat": "New procedures",
    "dot": "good",
    "goto": "workflows",
    "wf": "insurance-renewal",
    "html": "New procedure mapped: <b>Insurance certificate renewal tracking</b> \u00b7 34 runs"
   },
   {
    "cat": "AI firsts",
    "dot": "steel",
    "goto": "workflows",
    "wf": "rfp-bid",
    "html": "AI observed inside <b>Customer RFP and lane bid response</b> for the first time"
   },
   {
    "cat": "AI firsts",
    "dot": "steel",
    "goto": "workflows",
    "wf": "detention-capture",
    "html": "AI observed inside <b>Detention and accessorial capture</b> for the first time"
   },
   {
    "cat": "Activity",
    "dot": "warn",
    "goto": "workflows",
    "wf": "spot-quoting",
    "html": "<b>Spot rate quoting</b>: 4 runs, below its usual 8 to 16 a day \u00b7 2 days running"
   },
   {
    "cat": "Activity",
    "dot": "good",
    "goto": "workflows",
    "wf": "carrier-invoice-recon",
    "html": "<b>Carrier invoice reconciliation</b>: 14 runs, above its usual 2 to 6 a day"
   },
   {
    "cat": "Activity",
    "dot": "mist",
    "html": "Every other procedure ran within its usual daily range"
   }
  ]
 },
 "workflows": [
  {
   "id": "load-building",
   "name": "Load building and carrier assignment",
   "summary": "Dispatch turns each tendered load into a covered one: vetting carriers on DAT One, negotiating the rate by email, and assigning the carrier in McLeod. The highest-hours procedure in operations.",
   "inst": 312,
   "ppl": 12,
   "median": 78,
   "hours": 405.6,
   "ai": 3,
   "hasAi": true,
   "aiPpl": 2,
   "domain": "internal-ops",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-12",
   "cadence": [
    55,
    64,
    55,
    62,
    55,
    14,
    7
   ],
   "spread": {
    "lo": 13.3,
    "p10": 33.7,
    "q1": 49.9,
    "q3": 104.3,
    "p90": 161.3,
    "hi": 281.4
   },
   "apps": [
    "McLeod TMS",
    "DAT One",
    "Outlook",
    "Chrome"
   ],
   "appMix": [
    {
     "name": "McLeod TMS",
     "pct": 38
    },
    {
     "name": "DAT One",
     "pct": 27
    },
    {
     "name": "Outlook",
     "pct": 24
    },
    {
     "name": "Chrome",
     "pct": 7
    },
    {
     "name": "Other",
     "pct": 4,
     "other": true
    }
   ],
   "aiMedMin": 85.0,
   "plainMedMin": 77.8,
   "aiRunN": 9,
   "plainRunN": 303,
   "aiPplN": 2,
   "plainPplN": 11,
   "aiToolMedMin": 21.8,
   "aiHours": 12.8,
   "totalHours": 405.6,
   "phases": [
    {
     "text": "Review Tendered Loads",
     "sec": 806.9,
     "runs": 312,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Search Available Capacity",
     "sec": 1533.1,
     "runs": 312,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "DAT One",
      "Chrome"
     ],
     "aiHow": null
    },
    {
     "text": "Negotiate the Rate",
     "sec": 1533.1,
     "runs": 312,
     "aiPct": 3,
     "promptN": 22,
     "aiMin": 27.9,
     "plainMin": 25.6,
     "aiToolMin": 8.7,
     "aiN": 9,
     "plainN": 303,
     "aiPpl": 2,
     "plainPpl": 10,
     "systems": [
      "Outlook",
      "DAT One"
     ],
     "aiHow": {
      "usage": "Two dispatchers draft carrier rate emails with ChatGPT, then edit the number by hand before sending."
     }
    },
    {
     "text": "Assign and Dispatch",
     "sec": 806.9,
     "runs": 290,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "review-tenders",
     "name": "Review Tendered Loads",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "search-capacity",
     "name": "Search Available Capacity",
     "systems": [
      "DAT One",
      "Chrome"
     ],
     "core": true
    },
    {
     "id": "negotiate-rate",
     "name": "Negotiate the Rate",
     "systems": [
      "Outlook",
      "DAT One"
     ],
     "core": true
    },
    {
     "id": "assign-dispatch",
     "name": "Assign and Dispatch",
     "systems": [
      "McLeod TMS"
     ],
     "core": false
    }
   ],
   "alignedRuns": 312,
   "coverage": {
    "review-tenders": 100,
    "search-capacity": 93,
    "negotiate-rate": 86,
    "assign-dispatch": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Review Tendered Loads",
      "Search Available Capacity",
      "Negotiate the Rate",
      "Assign and Dispatch"
     ],
     "stepIds": [
      "review-tenders",
      "search-capacity",
      "negotiate-rate",
      "assign-dispatch"
     ],
     "runs": 119
    },
    {
     "steps": [
      "Review Tendered Loads",
      "Search Available Capacity",
      "Negotiate the Rate"
     ],
     "stepIds": [
      "review-tenders",
      "search-capacity",
      "negotiate-rate"
     ],
     "runs": 59
    },
    {
     "steps": [
      "Review Tendered Loads",
      "Negotiate the Rate",
      "Assign and Dispatch"
     ],
     "stepIds": [
      "review-tenders",
      "negotiate-rate",
      "assign-dispatch"
     ],
     "runs": 41
    },
    {
     "steps": [
      "Review Tendered Loads",
      "Assign and Dispatch"
     ],
     "stepIds": [
      "review-tenders",
      "assign-dispatch"
     ],
     "runs": 28
    }
   ],
   "shapesRemainder": 65,
   "aiSteps": {
    "negotiate-rate": {
     "runs": 9,
     "tool": "chatgpt",
     "usage": "Two dispatchers draft carrier rate emails with ChatGPT, then edit the number by hand before sending."
    }
   }
  },
  {
   "id": "spot-quoting",
   "name": "Spot rate quoting",
   "summary": "Analysts answer inbound lane quote requests: checking market rate in DAT One, building the number in the rate workbook, and replying by hand. The highest-volume procedure in the company.",
   "inst": 426,
   "ppl": 11,
   "median": 55,
   "hours": 390.5,
   "ai": 14,
   "hasAi": true,
   "aiPpl": 4,
   "domain": "quoting",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-12",
   "cadence": [
    148,
    128,
    53,
    43,
    43,
    11,
    0
   ],
   "spread": {
    "lo": 9.4,
    "p10": 20.9,
    "q1": 35.2,
    "q3": 83.6,
    "p90": 129.2,
    "hi": 225.5
   },
   "apps": [
    "Outlook",
    "DAT One",
    "Excel",
    "McLeod TMS"
   ],
   "appMix": [
    {
     "name": "Outlook",
     "pct": 31
    },
    {
     "name": "DAT One",
     "pct": 26
    },
    {
     "name": "Excel",
     "pct": 24
    },
    {
     "name": "McLeod TMS",
     "pct": 13
    },
    {
     "name": "Other",
     "pct": 6,
     "other": true
    }
   ],
   "aiMedMin": 44.6,
   "plainMedMin": 56.7,
   "aiRunN": 60,
   "plainRunN": 366,
   "aiPplN": 4,
   "plainPplN": 8,
   "aiToolMedMin": 15.4,
   "aiHours": 44.6,
   "totalHours": 390.5,
   "phases": [
    {
     "text": "Pull the Lane Request",
     "sec": 569.0,
     "runs": 426,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    },
    {
     "text": "Check Lane History and Market Rate",
     "sec": 1081.0,
     "runs": 426,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "DAT One",
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Build the Quote",
     "sec": 1081.0,
     "runs": 426,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Excel"
     ],
     "aiHow": null
    },
    {
     "text": "Send and Log the Quote",
     "sec": 569.0,
     "runs": 396,
     "aiPct": 14,
     "promptN": 144,
     "aiMin": 7.7,
     "plainMin": 9.5,
     "aiToolMin": 3.2,
     "aiN": 60,
     "plainN": 366,
     "aiPpl": 4,
     "plainPpl": 7,
     "systems": [
      "Outlook",
      "McLeod TMS"
     ],
     "aiHow": {
      "usage": "ChatGPT drafts the quote email around the finished number for four analysts, which is where most of the time on this step used to go."
     }
    }
   ],
   "trunk": [
    {
     "id": "pull-request",
     "name": "Pull the Lane Request",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "check-market",
     "name": "Check Lane History and Market Rate",
     "systems": [
      "DAT One",
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "build-quote",
     "name": "Build the Quote",
     "systems": [
      "Excel"
     ],
     "core": true
    },
    {
     "id": "send-log",
     "name": "Send and Log the Quote",
     "systems": [
      "Outlook",
      "McLeod TMS"
     ],
     "core": false
    }
   ],
   "alignedRuns": 426,
   "coverage": {
    "pull-request": 100,
    "check-market": 93,
    "build-quote": 86,
    "send-log": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Pull the Lane Request",
      "Check Lane History and Market Rate",
      "Build the Quote",
      "Send and Log the Quote"
     ],
     "stepIds": [
      "pull-request",
      "check-market",
      "build-quote",
      "send-log"
     ],
     "runs": 162
    },
    {
     "steps": [
      "Pull the Lane Request",
      "Check Lane History and Market Rate",
      "Build the Quote"
     ],
     "stepIds": [
      "pull-request",
      "check-market",
      "build-quote"
     ],
     "runs": 81
    },
    {
     "steps": [
      "Pull the Lane Request",
      "Build the Quote",
      "Send and Log the Quote"
     ],
     "stepIds": [
      "pull-request",
      "build-quote",
      "send-log"
     ],
     "runs": 55
    },
    {
     "steps": [
      "Pull the Lane Request",
      "Send and Log the Quote"
     ],
     "stepIds": [
      "pull-request",
      "send-log"
     ],
     "runs": 38
    }
   ],
   "shapesRemainder": 90,
   "aiSteps": {
    "send-log": {
     "runs": 60,
     "tool": "chatgpt",
     "usage": "ChatGPT drafts the quote email around the finished number for four analysts, which is where most of the time on this step used to go."
    }
   }
  },
  {
   "id": "invoice-audit",
   "name": "Customer invoice audit and dispute",
   "summary": "Billing reconciles flagged invoices line by line against the order and accessorials in McLeod, works the dispute with the customer, and posts the correction in QuickBooks.",
   "inst": 187,
   "ppl": 7,
   "median": 100,
   "hours": 311.7,
   "ai": 17,
   "hasAi": true,
   "aiPpl": 3,
   "domain": "finance",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-15",
   "cadence": [
    17,
    23,
    28,
    45,
    63,
    11,
    0
   ],
   "spread": {
    "lo": 17.0,
    "p10": 33.9,
    "q1": 64.0,
    "q3": 170.2,
    "p90": 263.2,
    "hi": 459.2
   },
   "apps": [
    "QuickBooks",
    "McLeod TMS",
    "Outlook",
    "Excel"
   ],
   "appMix": [
    {
     "name": "QuickBooks",
     "pct": 32
    },
    {
     "name": "McLeod TMS",
     "pct": 29
    },
    {
     "name": "Outlook",
     "pct": 22
    },
    {
     "name": "Excel",
     "pct": 12
    },
    {
     "name": "Other",
     "pct": 5,
     "other": true
    }
   ],
   "aiMedMin": 88.0,
   "plainMedMin": 102.5,
   "aiRunN": 32,
   "plainRunN": 155,
   "aiPplN": 3,
   "plainPplN": 5,
   "aiToolMedMin": 28.0,
   "aiHours": 46.9,
   "totalHours": 311.7,
   "phases": [
    {
     "text": "Pull Flagged Invoices",
     "sec": 1034.5,
     "runs": 187,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "QuickBooks"
     ],
     "aiHow": null
    },
    {
     "text": "Compare Lines to the Order",
     "sec": 1965.5,
     "runs": 187,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS",
      "Excel"
     ],
     "aiHow": null
    },
    {
     "text": "Work the Dispute",
     "sec": 1965.5,
     "runs": 187,
     "aiPct": 17,
     "promptN": 77,
     "aiMin": 28.8,
     "plainMin": 32.8,
     "aiToolMin": 11.1,
     "aiN": 32,
     "plainN": 155,
     "aiPpl": 3,
     "plainPpl": 4,
     "systems": [
      "Outlook"
     ],
     "aiHow": {
      "usage": "Three specialists paste the dispute thread into ChatGPT for a history summary before replying, rather than rereading the whole chain."
     }
    },
    {
     "text": "Post the Correction",
     "sec": 1034.5,
     "runs": 174,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "QuickBooks"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "pull-flagged",
     "name": "Pull Flagged Invoices",
     "systems": [
      "QuickBooks"
     ],
     "core": true
    },
    {
     "id": "compare-order",
     "name": "Compare Lines to the Order",
     "systems": [
      "McLeod TMS",
      "Excel"
     ],
     "core": true
    },
    {
     "id": "work-dispute",
     "name": "Work the Dispute",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "post-correction",
     "name": "Post the Correction",
     "systems": [
      "QuickBooks"
     ],
     "core": false
    }
   ],
   "alignedRuns": 187,
   "coverage": {
    "pull-flagged": 100,
    "compare-order": 93,
    "work-dispute": 86,
    "post-correction": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Pull Flagged Invoices",
      "Compare Lines to the Order",
      "Work the Dispute",
      "Post the Correction"
     ],
     "stepIds": [
      "pull-flagged",
      "compare-order",
      "work-dispute",
      "post-correction"
     ],
     "runs": 71
    },
    {
     "steps": [
      "Pull Flagged Invoices",
      "Compare Lines to the Order",
      "Work the Dispute"
     ],
     "stepIds": [
      "pull-flagged",
      "compare-order",
      "work-dispute"
     ],
     "runs": 36
    },
    {
     "steps": [
      "Pull Flagged Invoices",
      "Work the Dispute",
      "Post the Correction"
     ],
     "stepIds": [
      "pull-flagged",
      "work-dispute",
      "post-correction"
     ],
     "runs": 24
    },
    {
     "steps": [
      "Pull Flagged Invoices",
      "Post the Correction"
     ],
     "stepIds": [
      "pull-flagged",
      "post-correction"
     ],
     "runs": 17
    }
   ],
   "shapesRemainder": 39,
   "aiSteps": {
    "work-dispute": {
     "runs": 32,
     "tool": "chatgpt",
     "usage": "Three specialists paste the dispute thread into ChatGPT for a history summary before replying, rather than rereading the whole chain."
    }
   }
  },
  {
   "id": "pod-collection",
   "name": "Proof-of-delivery collection and billing release",
   "summary": "Operations sweeps carrier portals and the POD inbox for delivery documents, matches each to its order in McLeod, chases what is missing, and releases the order to billing.",
   "inst": 298,
   "ppl": 8,
   "median": 50,
   "hours": 248.3,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "domain": "documentation",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-13",
   "cadence": [
    53,
    62,
    53,
    61,
    53,
    8,
    8
   ],
   "spread": {
    "lo": 8.5,
    "p10": 20.2,
    "q1": 32.0,
    "q3": 71.4,
    "p90": 110.4,
    "hi": 192.7
   },
   "apps": [
    "Chrome",
    "McLeod TMS",
    "Outlook"
   ],
   "appMix": [
    {
     "name": "Chrome",
     "pct": 41
    },
    {
     "name": "McLeod TMS",
     "pct": 33
    },
    {
     "name": "Outlook",
     "pct": 21
    },
    {
     "name": "Other",
     "pct": 5,
     "other": true
    }
   ],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 298,
   "aiPplN": null,
   "plainPplN": 8,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 248.3,
   "phases": [
    {
     "text": "Sweep Portals and the POD Inbox",
     "sec": 517.2,
     "runs": 298,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Chrome",
      "Outlook"
     ],
     "aiHow": null
    },
    {
     "text": "Match Each Document to Its Order",
     "sec": 982.8,
     "runs": 298,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Chase Missing Documents",
     "sec": 982.8,
     "runs": 298,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    },
    {
     "text": "Verify and Release to Billing",
     "sec": 517.2,
     "runs": 277,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "sweep-portals",
     "name": "Sweep Portals and the POD Inbox",
     "systems": [
      "Chrome",
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "match-order",
     "name": "Match Each Document to Its Order",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "chase-missing",
     "name": "Chase Missing Documents",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "release-billing",
     "name": "Verify and Release to Billing",
     "systems": [
      "McLeod TMS"
     ],
     "core": false
    }
   ],
   "alignedRuns": 298,
   "coverage": {
    "sweep-portals": 100,
    "match-order": 93,
    "chase-missing": 86,
    "release-billing": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Sweep Portals and the POD Inbox",
      "Match Each Document to Its Order",
      "Chase Missing Documents",
      "Verify and Release to Billing"
     ],
     "stepIds": [
      "sweep-portals",
      "match-order",
      "chase-missing",
      "release-billing"
     ],
     "runs": 113
    },
    {
     "steps": [
      "Sweep Portals and the POD Inbox",
      "Match Each Document to Its Order",
      "Chase Missing Documents"
     ],
     "stepIds": [
      "sweep-portals",
      "match-order",
      "chase-missing"
     ],
     "runs": 57
    },
    {
     "steps": [
      "Sweep Portals and the POD Inbox",
      "Chase Missing Documents",
      "Verify and Release to Billing"
     ],
     "stepIds": [
      "sweep-portals",
      "chase-missing",
      "release-billing"
     ],
     "runs": 39
    },
    {
     "steps": [
      "Sweep Portals and the POD Inbox",
      "Verify and Release to Billing"
     ],
     "stepIds": [
      "sweep-portals",
      "release-billing"
     ],
     "runs": 27
    }
   ],
   "shapesRemainder": 62,
   "aiSteps": null
  },
  {
   "id": "carrier-invoice-recon",
   "name": "Carrier invoice reconciliation",
   "summary": "Accounts payable matches each incoming carrier invoice to its load and rate confirmation in McLeod, resolves mismatches with the carrier, and stages payment in QuickBooks.",
   "inst": 143,
   "ppl": 5,
   "median": 84,
   "hours": 200.2,
   "ai": 8,
   "hasAi": true,
   "aiPpl": 2,
   "domain": "finance",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-19",
   "cadence": [
    15,
    20,
    26,
    62,
    20,
    0,
    0
   ],
   "spread": {
    "lo": 14.3,
    "p10": 30.1,
    "q1": 53.8,
    "q3": 135.3,
    "p90": 209.2,
    "hi": 365.1
   },
   "apps": [
    "Outlook",
    "McLeod TMS",
    "Excel",
    "QuickBooks"
   ],
   "appMix": [
    {
     "name": "Outlook",
     "pct": 29
    },
    {
     "name": "McLeod TMS",
     "pct": 27
    },
    {
     "name": "Excel",
     "pct": 23
    },
    {
     "name": "QuickBooks",
     "pct": 21
    }
   ],
   "aiMedMin": 72.2,
   "plainMedMin": 85.0,
   "aiRunN": 11,
   "plainRunN": 132,
   "aiPplN": 2,
   "plainPplN": 4,
   "aiToolMedMin": 23.5,
   "aiHours": 13.2,
   "totalHours": 200.2,
   "phases": [
    {
     "text": "Pull the Week's Carrier Invoices",
     "sec": 869.0,
     "runs": 143,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    },
    {
     "text": "Match to Load and Rate Confirmation",
     "sec": 1651.0,
     "runs": 143,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Resolve Mismatches",
     "sec": 1651.0,
     "runs": 143,
     "aiPct": 8,
     "promptN": 26,
     "aiMin": 23.7,
     "plainMin": 27.5,
     "aiToolMin": 9.4,
     "aiN": 11,
     "plainN": 132,
     "aiPpl": 2,
     "plainPpl": 3,
     "systems": [
      "Outlook",
      "Excel"
     ],
     "aiHow": {
      "usage": "Copilot in Excel writes the mismatch summary two people send back to the carrier."
     }
    },
    {
     "text": "Approve and Stage Payment",
     "sec": 869.0,
     "runs": 133,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "QuickBooks"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "pull-invoices",
     "name": "Pull the Week's Carrier Invoices",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "match-rate-con",
     "name": "Match to Load and Rate Confirmation",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "resolve-mismatch",
     "name": "Resolve Mismatches",
     "systems": [
      "Outlook",
      "Excel"
     ],
     "core": true
    },
    {
     "id": "stage-payment",
     "name": "Approve and Stage Payment",
     "systems": [
      "QuickBooks"
     ],
     "core": false
    }
   ],
   "alignedRuns": 143,
   "coverage": {
    "pull-invoices": 100,
    "match-rate-con": 93,
    "resolve-mismatch": 86,
    "stage-payment": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Pull the Week's Carrier Invoices",
      "Match to Load and Rate Confirmation",
      "Resolve Mismatches",
      "Approve and Stage Payment"
     ],
     "stepIds": [
      "pull-invoices",
      "match-rate-con",
      "resolve-mismatch",
      "stage-payment"
     ],
     "runs": 54
    },
    {
     "steps": [
      "Pull the Week's Carrier Invoices",
      "Match to Load and Rate Confirmation",
      "Resolve Mismatches"
     ],
     "stepIds": [
      "pull-invoices",
      "match-rate-con",
      "resolve-mismatch"
     ],
     "runs": 27
    },
    {
     "steps": [
      "Pull the Week's Carrier Invoices",
      "Resolve Mismatches",
      "Approve and Stage Payment"
     ],
     "stepIds": [
      "pull-invoices",
      "resolve-mismatch",
      "stage-payment"
     ],
     "runs": 19
    },
    {
     "steps": [
      "Pull the Week's Carrier Invoices",
      "Approve and Stage Payment"
     ],
     "stepIds": [
      "pull-invoices",
      "stage-payment"
     ],
     "runs": 13
    }
   ],
   "shapesRemainder": 30,
   "aiSteps": {
    "resolve-mismatch": {
     "runs": 11,
     "tool": "copilot",
     "usage": "Copilot in Excel writes the mismatch summary two people send back to the carrier."
    }
   }
  },
  {
   "id": "track-and-trace",
   "name": "Load track-and-trace and status updates",
   "summary": "Dispatch runs check-calls and tracking updates through the day: pulling status from carrier portals and ELD links, updating each load in McLeod, and notifying the customer on exceptions.",
   "inst": 540,
   "ppl": 12,
   "median": 22,
   "hours": 198.0,
   "ai": 6,
   "hasAi": true,
   "aiPpl": 3,
   "domain": "customer-service",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-12",
   "cadence": [
    103,
    96,
    105,
    96,
    105,
    26,
    9
   ],
   "spread": {
    "lo": 3.7,
    "p10": 7.9,
    "q1": 14.1,
    "q3": 35.4,
    "p90": 54.8,
    "hi": 95.6
   },
   "apps": [
    "Chrome",
    "McLeod TMS",
    "Outlook"
   ],
   "appMix": [
    {
     "name": "Chrome",
     "pct": 39
    },
    {
     "name": "McLeod TMS",
     "pct": 34
    },
    {
     "name": "Outlook",
     "pct": 27
    }
   ],
   "aiMedMin": 18.5,
   "plainMedMin": 22.2,
   "aiRunN": 32,
   "plainRunN": 508,
   "aiPplN": 3,
   "plainPplN": 10,
   "aiToolMedMin": 6.2,
   "aiHours": 9.9,
   "totalHours": 198.0,
   "phases": [
    {
     "text": "Pull Status from Portals and ELD",
     "sec": 227.6,
     "runs": 540,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Chrome"
     ],
     "aiHow": null
    },
    {
     "text": "Update the Load Status and ETA",
     "sec": 432.4,
     "runs": 540,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Flag Any Exception or Delay",
     "sec": 432.4,
     "runs": 540,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Send the Status Update",
     "sec": 227.6,
     "runs": 502,
     "aiPct": 6,
     "promptN": 77,
     "aiMin": 3.2,
     "plainMin": 3.8,
     "aiToolMin": 1.3,
     "aiN": 32,
     "plainN": 508,
     "aiPpl": 3,
     "plainPpl": 9,
     "systems": [
      "Outlook"
     ],
     "aiHow": {
      "usage": "Copilot in Outlook drafts the exception notice for three dispatchers, who send dozens of these a day."
     }
    }
   ],
   "trunk": [
    {
     "id": "pull-status",
     "name": "Pull Status from Portals and ELD",
     "systems": [
      "Chrome"
     ],
     "core": true
    },
    {
     "id": "update-load",
     "name": "Update the Load Status and ETA",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "flag-exception",
     "name": "Flag Any Exception or Delay",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "notify-customer",
     "name": "Send the Status Update",
     "systems": [
      "Outlook"
     ],
     "core": false
    }
   ],
   "alignedRuns": 540,
   "coverage": {
    "pull-status": 100,
    "update-load": 93,
    "flag-exception": 86,
    "notify-customer": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Pull Status from Portals and ELD",
      "Update the Load Status and ETA",
      "Flag Any Exception or Delay",
      "Send the Status Update"
     ],
     "stepIds": [
      "pull-status",
      "update-load",
      "flag-exception",
      "notify-customer"
     ],
     "runs": 205
    },
    {
     "steps": [
      "Pull Status from Portals and ELD",
      "Update the Load Status and ETA",
      "Flag Any Exception or Delay"
     ],
     "stepIds": [
      "pull-status",
      "update-load",
      "flag-exception"
     ],
     "runs": 103
    },
    {
     "steps": [
      "Pull Status from Portals and ELD",
      "Flag Any Exception or Delay",
      "Send the Status Update"
     ],
     "stepIds": [
      "pull-status",
      "flag-exception",
      "notify-customer"
     ],
     "runs": 70
    },
    {
     "steps": [
      "Pull Status from Portals and ELD",
      "Send the Status Update"
     ],
     "stepIds": [
      "pull-status",
      "notify-customer"
     ],
     "runs": 49
    }
   ],
   "shapesRemainder": 113,
   "aiSteps": {
    "notify-customer": {
     "runs": 32,
     "tool": "copilot",
     "usage": "Copilot in Outlook drafts the exception notice for three dispatchers, who send dozens of these a day."
    }
   }
  },
  {
   "id": "payment-application",
   "name": "Customer payment application and collections",
   "summary": "Billing applies incoming customer payments against open invoices in QuickBooks, researches short-pays and remittance mismatches, and works aging receivables with customers by email.",
   "inst": 164,
   "ppl": 5,
   "median": 69,
   "hours": 188.6,
   "ai": 5,
   "hasAi": true,
   "aiPpl": 2,
   "domain": "finance",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-21",
   "cadence": [
    23,
    29,
    35,
    42,
    29,
    6,
    0
   ],
   "spread": {
    "lo": 11.7,
    "p10": 23.4,
    "q1": 44.2,
    "q3": 117.5,
    "p90": 181.6,
    "hi": 316.8
   },
   "apps": [
    "QuickBooks",
    "Outlook",
    "Excel",
    "McLeod TMS"
   ],
   "appMix": [
    {
     "name": "QuickBooks",
     "pct": 41
    },
    {
     "name": "Outlook",
     "pct": 28
    },
    {
     "name": "Excel",
     "pct": 20
    },
    {
     "name": "McLeod TMS",
     "pct": 11
    }
   ],
   "aiMedMin": 65.5,
   "plainMedMin": 69.2,
   "aiRunN": 8,
   "plainRunN": 156,
   "aiPplN": 2,
   "plainPplN": 4,
   "aiToolMedMin": 19.3,
   "aiHours": 8.7,
   "totalHours": 188.6,
   "phases": [
    {
     "text": "Match Payments to Open Invoices",
     "sec": 713.8,
     "runs": 164,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "QuickBooks",
      "Excel"
     ],
     "aiHow": null
    },
    {
     "text": "Apply Payments and Resolve Short-Pays",
     "sec": 1356.2,
     "runs": 164,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "QuickBooks"
     ],
     "aiHow": null
    },
    {
     "text": "Research Remittance Mismatches",
     "sec": 1356.2,
     "runs": 164,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Excel",
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Chase Aging Receivables",
     "sec": 713.8,
     "runs": 153,
     "aiPct": 5,
     "promptN": 19,
     "aiMin": 11.3,
     "plainMin": 11.9,
     "aiToolMin": 4.0,
     "aiN": 8,
     "plainN": 156,
     "aiPpl": 2,
     "plainPpl": 3,
     "systems": [
      "Outlook"
     ],
     "aiHow": {
      "usage": "Two collectors draft the aging follow-up with ChatGPT rather than rewriting the same note per customer."
     }
    }
   ],
   "trunk": [
    {
     "id": "match-remittance",
     "name": "Match Payments to Open Invoices",
     "systems": [
      "QuickBooks",
      "Excel"
     ],
     "core": true
    },
    {
     "id": "apply-payments",
     "name": "Apply Payments and Resolve Short-Pays",
     "systems": [
      "QuickBooks"
     ],
     "core": true
    },
    {
     "id": "research-mismatch",
     "name": "Research Remittance Mismatches",
     "systems": [
      "Excel",
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "chase-aging",
     "name": "Chase Aging Receivables",
     "systems": [
      "Outlook"
     ],
     "core": false
    }
   ],
   "alignedRuns": 164,
   "coverage": {
    "match-remittance": 100,
    "apply-payments": 93,
    "research-mismatch": 86,
    "chase-aging": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Match Payments to Open Invoices",
      "Apply Payments and Resolve Short-Pays",
      "Research Remittance Mismatches",
      "Chase Aging Receivables"
     ],
     "stepIds": [
      "match-remittance",
      "apply-payments",
      "research-mismatch",
      "chase-aging"
     ],
     "runs": 62
    },
    {
     "steps": [
      "Match Payments to Open Invoices",
      "Apply Payments and Resolve Short-Pays",
      "Research Remittance Mismatches"
     ],
     "stepIds": [
      "match-remittance",
      "apply-payments",
      "research-mismatch"
     ],
     "runs": 31
    },
    {
     "steps": [
      "Match Payments to Open Invoices",
      "Research Remittance Mismatches",
      "Chase Aging Receivables"
     ],
     "stepIds": [
      "match-remittance",
      "research-mismatch",
      "chase-aging"
     ],
     "runs": 21
    },
    {
     "steps": [
      "Match Payments to Open Invoices",
      "Chase Aging Receivables"
     ],
     "stepIds": [
      "match-remittance",
      "chase-aging"
     ],
     "runs": 15
    }
   ],
   "shapesRemainder": 35,
   "aiSteps": {
    "chase-aging": {
     "runs": 8,
     "tool": "chatgpt",
     "usage": "Two collectors draft the aging follow-up with ChatGPT rather than rewriting the same note per customer."
    }
   }
  },
  {
   "id": "appointment-scheduling",
   "name": "Pickup and delivery appointment scheduling",
   "summary": "Operations books pickup and delivery appointments with shippers and receivers: checking facility hours and dock availability, securing a slot, and writing it back to the load in McLeod.",
   "inst": 318,
   "ppl": 9,
   "median": 30,
   "hours": 159.0,
   "ai": 4,
   "hasAi": true,
   "aiPpl": 2,
   "domain": "communication",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-14",
   "cadence": [
    65,
    58,
    65,
    58,
    58,
    14,
    0
   ],
   "spread": {
    "lo": 5.1,
    "p10": 13.0,
    "q1": 19.2,
    "q3": 40.1,
    "p90": 62.0,
    "hi": 108.2
   },
   "apps": [
    "Outlook",
    "McLeod TMS",
    "Chrome"
   ],
   "appMix": [
    {
     "name": "Outlook",
     "pct": 36
    },
    {
     "name": "McLeod TMS",
     "pct": 33
    },
    {
     "name": "Chrome",
     "pct": 31
    }
   ],
   "aiMedMin": 27.9,
   "plainMedMin": 30.1,
   "aiRunN": 13,
   "plainRunN": 305,
   "aiPplN": 2,
   "plainPplN": 8,
   "aiToolMedMin": 8.4,
   "aiHours": 6.0,
   "totalHours": 159.0,
   "phases": [
    {
     "text": "Identify Loads Needing Appointments",
     "sec": 310.3,
     "runs": 318,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Check Hours and Dock Availability",
     "sec": 589.7,
     "runs": 318,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Chrome",
      "Outlook"
     ],
     "aiHow": null
    },
    {
     "text": "Secure the Appointment Window",
     "sec": 589.7,
     "runs": 318,
     "aiPct": 4,
     "promptN": 31,
     "aiMin": 9.1,
     "plainMin": 9.8,
     "aiToolMin": 3.3,
     "aiN": 13,
     "plainN": 305,
     "aiPpl": 2,
     "plainPpl": 7,
     "systems": [
      "Outlook"
     ],
     "aiHow": {
      "usage": "Copilot drafts the scheduling request for two schedulers when the facility only takes email."
     }
    },
    {
     "text": "Record It Against the Load",
     "sec": 310.3,
     "runs": 296,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "identify-loads",
     "name": "Identify Loads Needing Appointments",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "check-facility",
     "name": "Check Hours and Dock Availability",
     "systems": [
      "Chrome",
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "secure-slot",
     "name": "Secure the Appointment Window",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "record-appt",
     "name": "Record It Against the Load",
     "systems": [
      "McLeod TMS"
     ],
     "core": false
    }
   ],
   "alignedRuns": 318,
   "coverage": {
    "identify-loads": 100,
    "check-facility": 93,
    "secure-slot": 86,
    "record-appt": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Identify Loads Needing Appointments",
      "Check Hours and Dock Availability",
      "Secure the Appointment Window",
      "Record It Against the Load"
     ],
     "stepIds": [
      "identify-loads",
      "check-facility",
      "secure-slot",
      "record-appt"
     ],
     "runs": 121
    },
    {
     "steps": [
      "Identify Loads Needing Appointments",
      "Check Hours and Dock Availability",
      "Secure the Appointment Window"
     ],
     "stepIds": [
      "identify-loads",
      "check-facility",
      "secure-slot"
     ],
     "runs": 60
    },
    {
     "steps": [
      "Identify Loads Needing Appointments",
      "Secure the Appointment Window",
      "Record It Against the Load"
     ],
     "stepIds": [
      "identify-loads",
      "secure-slot",
      "record-appt"
     ],
     "runs": 41
    },
    {
     "steps": [
      "Identify Loads Needing Appointments",
      "Record It Against the Load"
     ],
     "stepIds": [
      "identify-loads",
      "record-appt"
     ],
     "runs": 29
    }
   ],
   "shapesRemainder": 67,
   "aiSteps": {
    "secure-slot": {
     "runs": 13,
     "tool": "copilot",
     "usage": "Copilot drafts the scheduling request for two schedulers when the facility only takes email."
    }
   }
  },
  {
   "id": "rfp-bid",
   "name": "Customer RFP and lane bid response",
   "summary": "Pricing responds to customer RFP and bid packages: pulling historical lane costs, modeling target rates across dozens of lanes in the bid workbook, and returning the completed pricing file.",
   "inst": 28,
   "ppl": 5,
   "median": 304,
   "hours": 141.9,
   "ai": 22,
   "hasAi": true,
   "aiPpl": 2,
   "domain": "quoting",
   "steps": 4,
   "trunked": true,
   "disc": "2026-06-11",
   "cadence": [
    4,
    6,
    5,
    7,
    5,
    1,
    0
   ],
   "spread": {
    "lo": 51.7,
    "p10": 115.5,
    "q1": 194.6,
    "q3": 462.1,
    "p90": 714.4,
    "hi": 1246.4
   },
   "apps": [
    "Excel",
    "DAT One",
    "McLeod TMS",
    "Outlook"
   ],
   "appMix": [
    {
     "name": "Excel",
     "pct": 47
    },
    {
     "name": "DAT One",
     "pct": 22
    },
    {
     "name": "McLeod TMS",
     "pct": 18
    },
    {
     "name": "Outlook",
     "pct": 13
    }
   ],
   "aiMedMin": 273.6,
   "plainMedMin": 312.3,
   "aiRunN": 6,
   "plainRunN": 22,
   "aiPplN": 2,
   "plainPplN": 4,
   "aiToolMedMin": 85.1,
   "aiHours": 27.4,
   "totalHours": 141.9,
   "phases": [
    {
     "text": "Parse the Lane List",
     "sec": 3144.8,
     "runs": 28,
     "aiPct": 21,
     "promptN": 14,
     "aiMin": 47.2,
     "plainMin": 52.4,
     "aiToolMin": 17.8,
     "aiN": 6,
     "plainN": 22,
     "aiPpl": 2,
     "plainPpl": 3,
     "systems": [
      "Outlook",
      "Excel"
     ],
     "aiHow": {
      "usage": "Two analysts hand the RFP attachment to Claude to pull the lane list into a table instead of retyping it."
     }
    },
    {
     "text": "Pull Historical Cost and Market Rate",
     "sec": 5975.2,
     "runs": 28,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "DAT One",
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Model Target Rates and Margins",
     "sec": 5975.2,
     "runs": 28,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Excel"
     ],
     "aiHow": null
    },
    {
     "text": "Return the Completed Bid File",
     "sec": 3144.8,
     "runs": 26,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "parse-rfp",
     "name": "Parse the Lane List",
     "systems": [
      "Outlook",
      "Excel"
     ],
     "core": true
    },
    {
     "id": "pull-history",
     "name": "Pull Historical Cost and Market Rate",
     "systems": [
      "DAT One",
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "model-rates",
     "name": "Model Target Rates and Margins",
     "systems": [
      "Excel"
     ],
     "core": true
    },
    {
     "id": "return-file",
     "name": "Return the Completed Bid File",
     "systems": [
      "Outlook"
     ],
     "core": false
    }
   ],
   "alignedRuns": 28,
   "coverage": {
    "parse-rfp": 100,
    "pull-history": 93,
    "model-rates": 86,
    "return-file": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Parse the Lane List",
      "Pull Historical Cost and Market Rate",
      "Model Target Rates and Margins",
      "Return the Completed Bid File"
     ],
     "stepIds": [
      "parse-rfp",
      "pull-history",
      "model-rates",
      "return-file"
     ],
     "runs": 11
    },
    {
     "steps": [
      "Parse the Lane List",
      "Pull Historical Cost and Market Rate",
      "Model Target Rates and Margins"
     ],
     "stepIds": [
      "parse-rfp",
      "pull-history",
      "model-rates"
     ],
     "runs": 5
    },
    {
     "steps": [
      "Parse the Lane List",
      "Model Target Rates and Margins",
      "Return the Completed Bid File"
     ],
     "stepIds": [
      "parse-rfp",
      "model-rates",
      "return-file"
     ],
     "runs": 4
    },
    {
     "steps": [
      "Parse the Lane List",
      "Return the Completed Bid File"
     ],
     "stepIds": [
      "parse-rfp",
      "return-file"
     ],
     "runs": 3
    }
   ],
   "shapesRemainder": 5,
   "aiSteps": {
    "parse-rfp": {
     "runs": 6,
     "tool": "claude",
     "usage": "Two analysts hand the RFP attachment to Claude to pull the lane list into a table instead of retyping it."
    }
   }
  },
  {
   "id": "carrier-onboarding",
   "name": "Carrier onboarding and compliance check",
   "summary": "Onboarding a carrier means collecting the authority, insurance and W-9 packet, verifying safety on FMCSA SAFER, summarizing the documents, and building the profile in McLeod. The most AI-touched procedure in the company.",
   "inst": 41,
   "ppl": 9,
   "median": 140,
   "hours": 95.7,
   "ai": 59,
   "hasAi": true,
   "aiPpl": 6,
   "domain": "procurement",
   "steps": 5,
   "trunked": true,
   "disc": "2026-06-02",
   "cadence": [
    7,
    0,
    15,
    4,
    11,
    0,
    4
   ],
   "spread": {
    "lo": 23.8,
    "p10": 60.5,
    "q1": 89.6,
    "q3": 187.3,
    "p90": 289.5,
    "hi": 505.1
   },
   "apps": [
    "Chrome",
    "Outlook",
    "McLeod TMS"
   ],
   "appMix": [
    {
     "name": "Chrome",
     "pct": 44
    },
    {
     "name": "Outlook",
     "pct": 28
    },
    {
     "name": "McLeod TMS",
     "pct": 22
    },
    {
     "name": "Other",
     "pct": 6,
     "other": true
    }
   ],
   "aiMedMin": 99.4,
   "plainMedMin": 197.3,
   "aiRunN": 24,
   "plainRunN": 17,
   "aiPplN": 6,
   "plainPplN": 4,
   "aiToolMedMin": 39.2,
   "aiHours": 39.8,
   "totalHours": 95.7,
   "phases": [
    {
     "text": "Collect the Carrier Packet",
     "sec": 1090.9,
     "runs": 41,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    },
    {
     "text": "Verify Authority on FMCSA SAFER",
     "sec": 2072.7,
     "runs": 41,
     "aiPct": 20,
     "promptN": 19,
     "aiMin": 24.5,
     "plainMin": 34.5,
     "aiToolMin": 11.7,
     "aiN": 8,
     "plainN": 33,
     "aiPpl": 6,
     "plainPpl": 3,
     "systems": [
      "Chrome"
     ],
     "aiHow": {
      "usage": "Two people also ask ChatGPT to read the SAFER snapshot back to them rather than scanning the table themselves."
     }
    },
    {
     "text": "Summarize the Compliance Documents",
     "sec": 2072.7,
     "runs": 41,
     "aiPct": 59,
     "promptN": 58,
     "aiMin": 24.5,
     "plainMin": 34.5,
     "aiToolMin": 11.7,
     "aiN": 24,
     "plainN": 17,
     "aiPpl": 6,
     "plainPpl": 3,
     "systems": [
      "Chrome"
     ],
     "aiHow": {
      "usage": "Six people paste insurance certificates and authority letters into ChatGPT and file the summary it returns. This step is now almost entirely AI-run."
     }
    },
    {
     "text": "Create the Carrier Profile",
     "sec": 2072.7,
     "runs": 41,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Activate the Carrier",
     "sec": 1090.9,
     "runs": 38,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS",
      "Outlook"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "collect-packet",
     "name": "Collect the Carrier Packet",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "verify-safer",
     "name": "Verify Authority on FMCSA SAFER",
     "systems": [
      "Chrome"
     ],
     "core": true
    },
    {
     "id": "summarize-docs",
     "name": "Summarize the Compliance Documents",
     "systems": [
      "Chrome"
     ],
     "core": true
    },
    {
     "id": "build-profile",
     "name": "Create the Carrier Profile",
     "systems": [
      "McLeod TMS"
     ],
     "core": false
    },
    {
     "id": "activate",
     "name": "Activate the Carrier",
     "systems": [
      "McLeod TMS",
      "Outlook"
     ],
     "core": false
    }
   ],
   "alignedRuns": 41,
   "coverage": {
    "collect-packet": 100,
    "verify-safer": 93,
    "summarize-docs": 86,
    "build-profile": 79,
    "activate": 98
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Collect the Carrier Packet",
      "Verify Authority on FMCSA SAFER",
      "Summarize the Compliance Documents",
      "Create the Carrier Profile",
      "Activate the Carrier"
     ],
     "stepIds": [
      "collect-packet",
      "verify-safer",
      "summarize-docs",
      "build-profile",
      "activate"
     ],
     "runs": 16
    },
    {
     "steps": [
      "Collect the Carrier Packet",
      "Verify Authority on FMCSA SAFER",
      "Summarize the Compliance Documents",
      "Create the Carrier Profile"
     ],
     "stepIds": [
      "collect-packet",
      "verify-safer",
      "summarize-docs",
      "build-profile"
     ],
     "runs": 8
    },
    {
     "steps": [
      "Collect the Carrier Packet",
      "Summarize the Compliance Documents",
      "Create the Carrier Profile",
      "Activate the Carrier"
     ],
     "stepIds": [
      "collect-packet",
      "summarize-docs",
      "build-profile",
      "activate"
     ],
     "runs": 5
    },
    {
     "steps": [
      "Collect the Carrier Packet",
      "Activate the Carrier"
     ],
     "stepIds": [
      "collect-packet",
      "activate"
     ],
     "runs": 4
    }
   ],
   "shapesRemainder": 8,
   "aiSteps": {
    "summarize-docs": {
     "runs": 24,
     "tool": "chatgpt",
     "usage": "Six people paste insurance certificates and authority letters into ChatGPT and file the summary it returns. This step is now almost entirely AI-run."
    },
    "verify-safer": {
     "runs": 8,
     "tool": "chatgpt",
     "usage": "Two people also ask ChatGPT to read the SAFER snapshot back to them rather than scanning the table themselves."
    }
   }
  },
  {
   "id": "claims-intake",
   "name": "Claims intake and OS&D",
   "summary": "Claims takes in an OS&D or damage report, flags the order in McLeod, gathers photos, PODs and carrier statements by email, and logs the case for resolution.",
   "inst": 38,
   "ppl": 4,
   "median": 133,
   "hours": 84.2,
   "ai": 50,
   "hasAi": true,
   "aiPpl": 3,
   "domain": "customer-service",
   "steps": 4,
   "trunked": true,
   "disc": "2026-06-05",
   "cadence": [
    3,
    10,
    0,
    7,
    15,
    3,
    0
   ],
   "spread": {
    "lo": 22.6,
    "p10": 50.5,
    "q1": 85.1,
    "q3": 202.2,
    "p90": 312.6,
    "hi": 545.3
   },
   "apps": [
    "Outlook",
    "McLeod TMS",
    "Excel",
    "Chrome"
   ],
   "appMix": [
    {
     "name": "Outlook",
     "pct": 43
    },
    {
     "name": "McLeod TMS",
     "pct": 34
    },
    {
     "name": "Excel",
     "pct": 16
    },
    {
     "name": "Chrome",
     "pct": 7
    }
   ],
   "aiMedMin": 105.1,
   "plainMedMin": 160.9,
   "aiRunN": 19,
   "plainRunN": 19,
   "aiPplN": 3,
   "plainPplN": 2,
   "aiToolMedMin": 37.2,
   "aiHours": 33.3,
   "totalHours": 84.2,
   "phases": [
    {
     "text": "Take the Damage Report In",
     "sec": 1375.9,
     "runs": 38,
     "aiPct": 50,
     "promptN": 46,
     "aiMin": 18.1,
     "plainMin": 22.9,
     "aiToolMin": 7.8,
     "aiN": 19,
     "plainN": 19,
     "aiPpl": 3,
     "plainPpl": 1,
     "systems": [
      "Outlook"
     ],
     "aiHow": {
      "usage": "Three specialists draft the claim acknowledgement with ChatGPT, which is the part of intake the customer sees first."
     }
    },
    {
     "text": "Flag the Order and Document It",
     "sec": 2614.1,
     "runs": 38,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Gather Photos and Statements",
     "sec": 2614.1,
     "runs": 38,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook",
      "Chrome"
     ],
     "aiHow": null
    },
    {
     "text": "Log the Case for Resolution",
     "sec": 1375.9,
     "runs": 35,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Excel",
      "McLeod TMS"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "take-report",
     "name": "Take the Damage Report In",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "flag-order",
     "name": "Flag the Order and Document It",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "gather-proof",
     "name": "Gather Photos and Statements",
     "systems": [
      "Outlook",
      "Chrome"
     ],
     "core": true
    },
    {
     "id": "log-case",
     "name": "Log the Case for Resolution",
     "systems": [
      "Excel",
      "McLeod TMS"
     ],
     "core": false
    }
   ],
   "alignedRuns": 38,
   "coverage": {
    "take-report": 100,
    "flag-order": 93,
    "gather-proof": 86,
    "log-case": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Take the Damage Report In",
      "Flag the Order and Document It",
      "Gather Photos and Statements",
      "Log the Case for Resolution"
     ],
     "stepIds": [
      "take-report",
      "flag-order",
      "gather-proof",
      "log-case"
     ],
     "runs": 14
    },
    {
     "steps": [
      "Take the Damage Report In",
      "Flag the Order and Document It",
      "Gather Photos and Statements"
     ],
     "stepIds": [
      "take-report",
      "flag-order",
      "gather-proof"
     ],
     "runs": 7
    },
    {
     "steps": [
      "Take the Damage Report In",
      "Gather Photos and Statements",
      "Log the Case for Resolution"
     ],
     "stepIds": [
      "take-report",
      "gather-proof",
      "log-case"
     ],
     "runs": 5
    },
    {
     "steps": [
      "Take the Damage Report In",
      "Log the Case for Resolution"
     ],
     "stepIds": [
      "take-report",
      "log-case"
     ],
     "runs": 3
    }
   ],
   "shapesRemainder": 9,
   "aiSteps": {
    "take-report": {
     "runs": 19,
     "tool": "chatgpt",
     "usage": "Three specialists draft the claim acknowledgement with ChatGPT, which is the part of intake the customer sees first."
    }
   }
  },
  {
   "id": "detention-capture",
   "name": "Detention and accessorial capture",
   "summary": "Operations captures detention and accessorial charges: gathering arrival and departure times and supporting documents, validating the charge against the rate confirmation, and submitting it for billing.",
   "inst": 73,
   "ppl": 8,
   "median": 58,
   "hours": 70.6,
   "ai": 9,
   "hasAi": true,
   "aiPpl": 2,
   "domain": "internal-ops",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-30",
   "cadence": [
    13,
    13,
    17,
    13,
    13,
    4,
    0
   ],
   "spread": {
    "lo": 9.9,
    "p10": 25.0,
    "q1": 37.1,
    "q3": 77.6,
    "p90": 119.9,
    "hi": 209.3
   },
   "apps": [
    "McLeod TMS",
    "Outlook",
    "Chrome",
    "Excel"
   ],
   "appMix": [
    {
     "name": "McLeod TMS",
     "pct": 37
    },
    {
     "name": "Outlook",
     "pct": 31
    },
    {
     "name": "Chrome",
     "pct": 20
    },
    {
     "name": "Excel",
     "pct": 12
    }
   ],
   "aiMedMin": 52.8,
   "plainMedMin": 58.6,
   "aiRunN": 7,
   "plainRunN": 66,
   "aiPplN": 2,
   "plainPplN": 7,
   "aiToolMedMin": 16.2,
   "aiHours": 6.2,
   "totalHours": 70.6,
   "phases": [
    {
     "text": "Identify Loads with Exposure",
     "sec": 600.0,
     "runs": 73,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Gather Times and Documents",
     "sec": 1140.0,
     "runs": 73,
     "aiPct": 10,
     "promptN": 17,
     "aiMin": 17.3,
     "plainMin": 19.0,
     "aiToolMin": 6.5,
     "aiN": 7,
     "plainN": 66,
     "aiPpl": 2,
     "plainPpl": 6,
     "systems": [
      "Chrome",
      "Outlook"
     ],
     "aiHow": {
      "usage": "Two people summarize the driver and facility email chain with ChatGPT to pull the arrival and departure times out of it."
     }
    },
    {
     "text": "Validate Against the Rate Confirmation",
     "sec": 1140.0,
     "runs": 73,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS",
      "Excel"
     ],
     "aiHow": null
    },
    {
     "text": "Submit the Accessorial",
     "sec": 600.0,
     "runs": 68,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "identify-exposure",
     "name": "Identify Loads with Exposure",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "gather-times",
     "name": "Gather Times and Documents",
     "systems": [
      "Chrome",
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "validate-charge",
     "name": "Validate Against the Rate Confirmation",
     "systems": [
      "McLeod TMS",
      "Excel"
     ],
     "core": true
    },
    {
     "id": "submit-billing",
     "name": "Submit the Accessorial",
     "systems": [
      "McLeod TMS"
     ],
     "core": false
    }
   ],
   "alignedRuns": 73,
   "coverage": {
    "identify-exposure": 100,
    "gather-times": 93,
    "validate-charge": 86,
    "submit-billing": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Identify Loads with Exposure",
      "Gather Times and Documents",
      "Validate Against the Rate Confirmation",
      "Submit the Accessorial"
     ],
     "stepIds": [
      "identify-exposure",
      "gather-times",
      "validate-charge",
      "submit-billing"
     ],
     "runs": 28
    },
    {
     "steps": [
      "Identify Loads with Exposure",
      "Gather Times and Documents",
      "Validate Against the Rate Confirmation"
     ],
     "stepIds": [
      "identify-exposure",
      "gather-times",
      "validate-charge"
     ],
     "runs": 14
    },
    {
     "steps": [
      "Identify Loads with Exposure",
      "Validate Against the Rate Confirmation",
      "Submit the Accessorial"
     ],
     "stepIds": [
      "identify-exposure",
      "validate-charge",
      "submit-billing"
     ],
     "runs": 9
    },
    {
     "steps": [
      "Identify Loads with Exposure",
      "Submit the Accessorial"
     ],
     "stepIds": [
      "identify-exposure",
      "submit-billing"
     ],
     "runs": 7
    }
   ],
   "shapesRemainder": 15,
   "aiSteps": {
    "gather-times": {
     "runs": 7,
     "tool": "chatgpt",
     "usage": "Two people summarize the driver and facility email chain with ChatGPT to pull the arrival and departure times out of it."
    }
   }
  },
  {
   "id": "quick-pay",
   "name": "Carrier quick-pay processing",
   "summary": "Accounts payable processes carrier quick-pay requests: verifying the load and proof-of-delivery, calculating the quick-pay discount, and staging the accelerated payment in QuickBooks.",
   "inst": 96,
   "ppl": 4,
   "median": 40,
   "hours": 64.0,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "domain": "finance",
   "steps": 4,
   "trunked": true,
   "disc": "2026-05-27",
   "cadence": [
    18,
    18,
    24,
    18,
    18,
    0,
    0
   ],
   "spread": {
    "lo": 6.8,
    "p10": 16.2,
    "q1": 25.6,
    "q3": 57.2,
    "p90": 88.4,
    "hi": 154.2
   },
   "apps": [
    "QuickBooks",
    "McLeod TMS",
    "Outlook"
   ],
   "appMix": [
    {
     "name": "QuickBooks",
     "pct": 38
    },
    {
     "name": "McLeod TMS",
     "pct": 32
    },
    {
     "name": "Outlook",
     "pct": 30
    }
   ],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 96,
   "aiPplN": null,
   "plainPplN": 4,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 64.0,
   "phases": [
    {
     "text": "Receive the Quick-Pay Request",
     "sec": 413.8,
     "runs": 96,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    },
    {
     "text": "Verify the Load and POD",
     "sec": 786.2,
     "runs": 96,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Calculate the Discount and Net",
     "sec": 786.2,
     "runs": 96,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "QuickBooks"
     ],
     "aiHow": null
    },
    {
     "text": "Stage the Accelerated Payment",
     "sec": 413.8,
     "runs": 89,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "QuickBooks"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "receive-request",
     "name": "Receive the Quick-Pay Request",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "verify-pod",
     "name": "Verify the Load and POD",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "calc-discount",
     "name": "Calculate the Discount and Net",
     "systems": [
      "QuickBooks"
     ],
     "core": true
    },
    {
     "id": "stage-accelerated",
     "name": "Stage the Accelerated Payment",
     "systems": [
      "QuickBooks"
     ],
     "core": false
    }
   ],
   "alignedRuns": 96,
   "coverage": {
    "receive-request": 100,
    "verify-pod": 93,
    "calc-discount": 86,
    "stage-accelerated": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Receive the Quick-Pay Request",
      "Verify the Load and POD",
      "Calculate the Discount and Net",
      "Stage the Accelerated Payment"
     ],
     "stepIds": [
      "receive-request",
      "verify-pod",
      "calc-discount",
      "stage-accelerated"
     ],
     "runs": 36
    },
    {
     "steps": [
      "Receive the Quick-Pay Request",
      "Verify the Load and POD",
      "Calculate the Discount and Net"
     ],
     "stepIds": [
      "receive-request",
      "verify-pod",
      "calc-discount"
     ],
     "runs": 18
    },
    {
     "steps": [
      "Receive the Quick-Pay Request",
      "Calculate the Discount and Net",
      "Stage the Accelerated Payment"
     ],
     "stepIds": [
      "receive-request",
      "calc-discount",
      "stage-accelerated"
     ],
     "runs": 12
    },
    {
     "steps": [
      "Receive the Quick-Pay Request",
      "Stage the Accelerated Payment"
     ],
     "stepIds": [
      "receive-request",
      "stage-accelerated"
     ],
     "runs": 9
    }
   ],
   "shapesRemainder": 21,
   "aiSteps": null
  },
  {
   "id": "margin-report",
   "name": "Weekly margin report assembly",
   "summary": "Pricing exports the week's revenue and cost data from McLeod, loads it into the margin workbook, builds the summary and variance notes, and distributes the report to leadership.",
   "inst": 14,
   "ppl": 2,
   "median": 207,
   "hours": 48.3,
   "ai": 86,
   "hasAi": true,
   "aiPpl": 2,
   "domain": "reporting",
   "steps": 4,
   "trunked": true,
   "disc": "2026-06-09",
   "cadence": [
    0,
    0,
    1,
    1,
    12,
    0,
    0
   ],
   "spread": {
    "lo": 35.2,
    "p10": 83.7,
    "q1": 132.5,
    "q3": 295.8,
    "p90": 457.3,
    "hi": 797.8
   },
   "apps": [
    "Excel",
    "McLeod TMS",
    "Outlook"
   ],
   "appMix": [
    {
     "name": "Excel",
     "pct": 58
    },
    {
     "name": "McLeod TMS",
     "pct": 27
    },
    {
     "name": "Outlook",
     "pct": 15
    }
   ],
   "aiMedMin": 207.0,
   "plainMedMin": 207.0,
   "aiRunN": 12,
   "plainRunN": 2,
   "aiPplN": 2,
   "plainPplN": 1,
   "aiToolMedMin": 58.0,
   "aiHours": 41.4,
   "totalHours": 48.3,
   "phases": [
    {
     "text": "Export the Week's Revenue Data",
     "sec": 2141.4,
     "runs": 14,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Load the Extract into the Workbook",
     "sec": 4068.6,
     "runs": 14,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Excel"
     ],
     "aiHow": null
    },
    {
     "text": "Build the Summary and Variance Notes",
     "sec": 4068.6,
     "runs": 14,
     "aiPct": 86,
     "promptN": 29,
     "aiMin": 67.8,
     "plainMin": 67.8,
     "aiToolMin": 23.1,
     "aiN": 12,
     "plainN": 2,
     "aiPpl": 2,
     "plainPpl": 0,
     "systems": [
      "Excel"
     ],
     "aiHow": {
      "usage": "Copilot assembles the summary tabs and writes the variance notes. Both people who run this report have used it every week since it was mapped, so there is no meaningful comparison left to draw."
     }
    },
    {
     "text": "Distribute to Leadership",
     "sec": 2141.4,
     "runs": 13,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "export-data",
     "name": "Export the Week's Revenue Data",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "load-workbook",
     "name": "Load the Extract into the Workbook",
     "systems": [
      "Excel"
     ],
     "core": true
    },
    {
     "id": "build-summary",
     "name": "Build the Summary and Variance Notes",
     "systems": [
      "Excel"
     ],
     "core": true
    },
    {
     "id": "distribute",
     "name": "Distribute to Leadership",
     "systems": [
      "Outlook"
     ],
     "core": false
    }
   ],
   "alignedRuns": 14,
   "coverage": {
    "export-data": 100,
    "load-workbook": 93,
    "build-summary": 86,
    "distribute": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Export the Week's Revenue Data",
      "Load the Extract into the Workbook",
      "Build the Summary and Variance Notes",
      "Distribute to Leadership"
     ],
     "stepIds": [
      "export-data",
      "load-workbook",
      "build-summary",
      "distribute"
     ],
     "runs": 5
    },
    {
     "steps": [
      "Export the Week's Revenue Data",
      "Load the Extract into the Workbook",
      "Build the Summary and Variance Notes"
     ],
     "stepIds": [
      "export-data",
      "load-workbook",
      "build-summary"
     ],
     "runs": 3
    },
    {
     "steps": [
      "Export the Week's Revenue Data",
      "Build the Summary and Variance Notes",
      "Distribute to Leadership"
     ],
     "stepIds": [
      "export-data",
      "build-summary",
      "distribute"
     ],
     "runs": 2
    }
   ],
   "shapesRemainder": 4,
   "aiSteps": {
    "build-summary": {
     "runs": 12,
     "tool": "copilot",
     "usage": "Copilot assembles the summary tabs and writes the variance notes. Both people who run this report have used it every week since it was mapped, so there is no meaningful comparison left to draw."
    }
   }
  },
  {
   "id": "credit-setup",
   "name": "New customer credit setup",
   "summary": "Billing receives a credit application from sales, pulls the credit report and trade references, sets terms and a limit in QuickBooks, and activates the customer in McLeod.",
   "inst": 22,
   "ppl": 3,
   "median": 112,
   "hours": 41.1,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "domain": "finance",
   "steps": 4,
   "trunked": true,
   "disc": "2026-06-16",
   "cadence": [
    0,
    7,
    4,
    0,
    7,
    0,
    4
   ],
   "spread": {
    "lo": 19.0,
    "p10": 38.0,
    "q1": 71.7,
    "q3": 190.7,
    "p90": 294.8,
    "hi": 514.3
   },
   "apps": [
    "Chrome",
    "QuickBooks",
    "Outlook",
    "McLeod TMS"
   ],
   "appMix": [
    {
     "name": "Chrome",
     "pct": 34
    },
    {
     "name": "QuickBooks",
     "pct": 30
    },
    {
     "name": "Outlook",
     "pct": 24
    },
    {
     "name": "McLeod TMS",
     "pct": 12
    }
   ],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 22,
   "aiPplN": null,
   "plainPplN": 3,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 41.1,
   "phases": [
    {
     "text": "Receive the Credit Application",
     "sec": 1158.6,
     "runs": 22,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    },
    {
     "text": "Pull the Credit Report",
     "sec": 2201.4,
     "runs": 22,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Chrome"
     ],
     "aiHow": null
    },
    {
     "text": "Set Terms and the Credit Limit",
     "sec": 2201.4,
     "runs": 22,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "QuickBooks"
     ],
     "aiHow": null
    },
    {
     "text": "Notify Sales and Activate",
     "sec": 1158.6,
     "runs": 20,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS",
      "Outlook"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "receive-app",
     "name": "Receive the Credit Application",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "pull-report",
     "name": "Pull the Credit Report",
     "systems": [
      "Chrome"
     ],
     "core": true
    },
    {
     "id": "set-terms",
     "name": "Set Terms and the Credit Limit",
     "systems": [
      "QuickBooks"
     ],
     "core": true
    },
    {
     "id": "activate-customer",
     "name": "Notify Sales and Activate",
     "systems": [
      "McLeod TMS",
      "Outlook"
     ],
     "core": false
    }
   ],
   "alignedRuns": 22,
   "coverage": {
    "receive-app": 100,
    "pull-report": 93,
    "set-terms": 86,
    "activate-customer": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Receive the Credit Application",
      "Pull the Credit Report",
      "Set Terms and the Credit Limit",
      "Notify Sales and Activate"
     ],
     "stepIds": [
      "receive-app",
      "pull-report",
      "set-terms",
      "activate-customer"
     ],
     "runs": 8
    },
    {
     "steps": [
      "Receive the Credit Application",
      "Pull the Credit Report",
      "Set Terms and the Credit Limit"
     ],
     "stepIds": [
      "receive-app",
      "pull-report",
      "set-terms"
     ],
     "runs": 4
    },
    {
     "steps": [
      "Receive the Credit Application",
      "Set Terms and the Credit Limit",
      "Notify Sales and Activate"
     ],
     "stepIds": [
      "receive-app",
      "set-terms",
      "activate-customer"
     ],
     "runs": 3
    },
    {
     "steps": [
      "Receive the Credit Application",
      "Notify Sales and Activate"
     ],
     "stepIds": [
      "receive-app",
      "activate-customer"
     ],
     "runs": 2
    }
   ],
   "shapesRemainder": 5,
   "aiSteps": null
  },
  {
   "id": "insurance-renewal",
   "name": "Insurance certificate renewal tracking",
   "summary": "Compliance tracks expiring carrier insurance certificates, requests renewals before they lapse, and verifies the new certificate meets coverage requirements before reactivating the carrier.",
   "inst": 34,
   "ppl": 3,
   "median": 67,
   "hours": 38.0,
   "ai": 31,
   "hasAi": true,
   "aiPpl": 2,
   "domain": "procurement",
   "steps": 4,
   "trunked": true,
   "disc": "2026-06-13",
   "cadence": [
    7,
    3,
    10,
    7,
    7,
    0,
    0
   ],
   "spread": {
    "lo": 11.4,
    "p10": 24.0,
    "q1": 42.9,
    "q3": 108.0,
    "p90": 166.9,
    "hi": 291.2
   },
   "apps": [
    "Outlook",
    "Chrome",
    "McLeod TMS"
   ],
   "appMix": [
    {
     "name": "Outlook",
     "pct": 40
    },
    {
     "name": "Chrome",
     "pct": 33
    },
    {
     "name": "McLeod TMS",
     "pct": 27
    }
   ],
   "aiMedMin": 50.9,
   "plainMedMin": 74.7,
   "aiRunN": 11,
   "plainRunN": 23,
   "aiPplN": 2,
   "plainPplN": 2,
   "aiToolMedMin": 18.8,
   "aiHours": 9.3,
   "totalHours": 38.0,
   "phases": [
    {
     "text": "Identify Expiring Certificates",
     "sec": 693.1,
     "runs": 34,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    },
    {
     "text": "Request the Renewed Certificate",
     "sec": 1316.9,
     "runs": 34,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    },
    {
     "text": "Verify Coverage Limits",
     "sec": 1316.9,
     "runs": 34,
     "aiPct": 32,
     "promptN": 26,
     "aiMin": 16.7,
     "plainMin": 21.9,
     "aiToolMin": 7.5,
     "aiN": 11,
     "plainN": 23,
     "aiPpl": 2,
     "plainPpl": 1,
     "systems": [
      "Chrome"
     ],
     "aiHow": {
      "usage": "Two people check the renewed certificate against the coverage requirement with ChatGPT instead of reading the policy schedule."
     }
    },
    {
     "text": "Update the Record and Reactivate",
     "sec": 693.1,
     "runs": 32,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "McLeod TMS"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "find-expiring",
     "name": "Identify Expiring Certificates",
     "systems": [
      "McLeod TMS"
     ],
     "core": true
    },
    {
     "id": "request-renewal",
     "name": "Request the Renewed Certificate",
     "systems": [
      "Outlook"
     ],
     "core": true
    },
    {
     "id": "verify-coverage",
     "name": "Verify Coverage Limits",
     "systems": [
      "Chrome"
     ],
     "core": true
    },
    {
     "id": "reactivate",
     "name": "Update the Record and Reactivate",
     "systems": [
      "McLeod TMS"
     ],
     "core": false
    }
   ],
   "alignedRuns": 34,
   "coverage": {
    "find-expiring": 100,
    "request-renewal": 93,
    "verify-coverage": 86,
    "reactivate": 79
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Identify Expiring Certificates",
      "Request the Renewed Certificate",
      "Verify Coverage Limits",
      "Update the Record and Reactivate"
     ],
     "stepIds": [
      "find-expiring",
      "request-renewal",
      "verify-coverage",
      "reactivate"
     ],
     "runs": 13
    },
    {
     "steps": [
      "Identify Expiring Certificates",
      "Request the Renewed Certificate",
      "Verify Coverage Limits"
     ],
     "stepIds": [
      "find-expiring",
      "request-renewal",
      "verify-coverage"
     ],
     "runs": 6
    },
    {
     "steps": [
      "Identify Expiring Certificates",
      "Verify Coverage Limits",
      "Update the Record and Reactivate"
     ],
     "stepIds": [
      "find-expiring",
      "verify-coverage",
      "reactivate"
     ],
     "runs": 4
    },
    {
     "steps": [
      "Identify Expiring Certificates",
      "Update the Record and Reactivate"
     ],
     "stepIds": [
      "find-expiring",
      "reactivate"
     ],
     "runs": 3
    }
   ],
   "shapesRemainder": 8,
   "aiSteps": {
    "verify-coverage": {
     "runs": 11,
     "tool": "chatgpt",
     "usage": "Two people check the renewed certificate against the coverage requirement with ChatGPT instead of reading the policy schedule."
    }
   }
  },
  {
   "id": "fuel-surcharge",
   "name": "Weekly fuel surcharge update",
   "summary": "Pricing updates the fuel surcharge schedule each week: pulling the published DOE diesel index, recalculating the table, and publishing the new rates to the team and customers.",
   "inst": 6,
   "ppl": 2,
   "median": 140,
   "hours": 14.0,
   "ai": 33,
   "hasAi": true,
   "aiPpl": 1,
   "domain": "reporting",
   "steps": 3,
   "trunked": true,
   "disc": "2026-06-18",
   "cadence": [
    0,
    1,
    0,
    5,
    0,
    0,
    0
   ],
   "spread": {
    "lo": 23.8,
    "p10": 53.2,
    "q1": 89.6,
    "q3": 212.8,
    "p90": 329.0,
    "hi": 574.0
   },
   "apps": [
    "Excel",
    "Chrome",
    "Outlook"
   ],
   "appMix": [
    {
     "name": "Excel",
     "pct": 52
    },
    {
     "name": "Chrome",
     "pct": 26
    },
    {
     "name": "Outlook",
     "pct": 22
    }
   ],
   "aiMedMin": 119.0,
   "plainMedMin": 150.5,
   "aiRunN": 2,
   "plainRunN": 4,
   "aiPplN": 1,
   "plainPplN": 2,
   "aiToolMedMin": 39.2,
   "aiHours": 4.0,
   "totalHours": 14.0,
   "phases": [
    {
     "text": "Pull the DOE Diesel Index",
     "sec": 2153.8,
     "runs": 6,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Chrome"
     ],
     "aiHow": null
    },
    {
     "text": "Recalculate the Surcharge Table",
     "sec": 4092.3,
     "runs": 6,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Excel"
     ],
     "aiHow": null
    },
    {
     "text": "Publish the New Rates",
     "sec": 2153.8,
     "runs": 6,
     "aiPct": 0,
     "promptN": 0,
     "aiMin": null,
     "plainMin": null,
     "aiToolMin": null,
     "aiN": null,
     "plainN": null,
     "aiPpl": null,
     "plainPpl": null,
     "systems": [
      "Outlook"
     ],
     "aiHow": null
    }
   ],
   "trunk": [
    {
     "id": "pull-index",
     "name": "Pull the DOE Diesel Index",
     "systems": [
      "Chrome"
     ],
     "core": true
    },
    {
     "id": "recalc-table",
     "name": "Recalculate the Surcharge Table",
     "systems": [
      "Excel"
     ],
     "core": true
    },
    {
     "id": "publish-rates",
     "name": "Publish the New Rates",
     "systems": [
      "Outlook"
     ],
     "core": true
    }
   ],
   "alignedRuns": 6,
   "coverage": {
    "pull-index": 100,
    "recalc-table": 93,
    "publish-rates": 86
   },
   "branches": [],
   "shapes": [
    {
     "steps": [
      "Pull the DOE Diesel Index",
      "Recalculate the Surcharge Table",
      "Publish the New Rates"
     ],
     "stepIds": [
      "pull-index",
      "recalc-table",
      "publish-rates"
     ],
     "runs": 2
    }
   ],
   "shapesRemainder": 4,
   "aiSteps": null
  },
  {
   "id": "tail-01",
   "name": "Filing a cargo insurance claim with the underwriter",
   "summary": "",
   "domain": "customer-service",
   "inst": 2,
   "ppl": 1,
   "median": 21.0,
   "hours": 0.7,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-21",
   "cadence": [
    2,
    0,
    0,
    0,
    0,
    0,
    0
   ],
   "spread": {
    "lo": 3.6,
    "p10": 8.0,
    "q1": 13.4,
    "q3": 31.9,
    "p90": 49.4,
    "hi": 86.1
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 2,
   "aiPplN": null,
   "plainPplN": 1,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.7,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-00",
   "name": "Setting up a new user in McLeod",
   "summary": "",
   "domain": "it-operations",
   "inst": 3,
   "ppl": 2,
   "median": 12.0,
   "hours": 0.6,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-20",
   "cadence": [
    -1,
    1,
    1,
    1,
    1,
    0,
    0
   ],
   "spread": {
    "lo": 2.0,
    "p10": 5.2,
    "q1": 7.7,
    "q3": 16.1,
    "p90": 24.8,
    "hi": 43.3
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 3,
   "aiPplN": null,
   "plainPplN": 2,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.6,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-02",
   "name": "Reconciling the corporate card statement",
   "summary": "",
   "domain": "finance",
   "inst": 2,
   "ppl": 1,
   "median": 18.0,
   "hours": 0.6,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-22",
   "cadence": [
    2,
    0,
    0,
    0,
    0,
    0,
    0
   ],
   "spread": {
    "lo": 3.1,
    "p10": 6.1,
    "q1": 11.5,
    "q3": 30.6,
    "p90": 47.4,
    "hi": 82.7
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 2,
   "aiPplN": null,
   "plainPplN": 1,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.6,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-05",
   "name": "Running the quarterly carrier scorecard",
   "summary": "",
   "domain": "reporting",
   "inst": 1,
   "ppl": 1,
   "median": 33.0,
   "hours": 0.6,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-25",
   "cadence": [
    1,
    0,
    0,
    0,
    0,
    0,
    0
   ],
   "spread": {
    "lo": 5.6,
    "p10": 14.3,
    "q1": 21.1,
    "q3": 44.1,
    "p90": 68.2,
    "hi": 119.1
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 1,
   "aiPplN": null,
   "plainPplN": 1,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.6,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-06",
   "name": "Renewing a lane contract with a shipper",
   "summary": "",
   "domain": "quoting",
   "inst": 3,
   "ppl": 2,
   "median": 11.0,
   "hours": 0.6,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-26",
   "cadence": [
    -1,
    1,
    1,
    1,
    1,
    0,
    0
   ],
   "spread": {
    "lo": 1.9,
    "p10": 4.2,
    "q1": 7.0,
    "q3": 16.7,
    "p90": 25.9,
    "hi": 45.1
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 3,
   "aiPplN": null,
   "plainPplN": 2,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.6,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-03",
   "name": "Updating the customer contact list",
   "summary": "",
   "domain": "documentation",
   "inst": 4,
   "ppl": 3,
   "median": 7.0,
   "hours": 0.5,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-23",
   "cadence": [
    0,
    1,
    1,
    1,
    1,
    0,
    0
   ],
   "spread": {
    "lo": 1.2,
    "p10": 2.8,
    "q1": 4.5,
    "q3": 10.0,
    "p90": 15.5,
    "hi": 27.0
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 4,
   "aiPplN": null,
   "plainPplN": 3,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.5,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-04",
   "name": "Onboarding a new dispatcher",
   "summary": "",
   "domain": "hr",
   "inst": 2,
   "ppl": 2,
   "median": 16.0,
   "hours": 0.5,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-24",
   "cadence": [
    2,
    0,
    0,
    0,
    0,
    0,
    0
   ],
   "spread": {
    "lo": 2.7,
    "p10": 5.7,
    "q1": 10.2,
    "q3": 25.8,
    "p90": 39.9,
    "hi": 69.5
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 2,
   "aiPplN": null,
   "plainPplN": 2,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.5,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-07",
   "name": "Registering a new customer in the load board",
   "summary": "",
   "domain": "internal-ops",
   "inst": 3,
   "ppl": 2,
   "median": 9.0,
   "hours": 0.5,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-27",
   "cadence": [
    -1,
    1,
    1,
    1,
    1,
    0,
    0
   ],
   "spread": {
    "lo": 1.5,
    "p10": 3.1,
    "q1": 5.8,
    "q3": 15.3,
    "p90": 23.7,
    "hi": 41.3
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 3,
   "aiPplN": null,
   "plainPplN": 2,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.5,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-11",
   "name": "Pulling a driver history for a safety review",
   "summary": "",
   "domain": "internal-ops",
   "inst": 2,
   "ppl": 1,
   "median": 14.0,
   "hours": 0.5,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-21",
   "cadence": [
    2,
    0,
    0,
    0,
    0,
    0,
    0
   ],
   "spread": {
    "lo": 2.4,
    "p10": 5.3,
    "q1": 9.0,
    "q3": 21.3,
    "p90": 32.9,
    "hi": 57.4
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 2,
   "aiPplN": null,
   "plainPplN": 1,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.5,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-08",
   "name": "Correcting a mis-keyed bill of lading",
   "summary": "",
   "domain": "documentation",
   "inst": 4,
   "ppl": 3,
   "median": 6.0,
   "hours": 0.4,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-28",
   "cadence": [
    0,
    1,
    1,
    1,
    1,
    0,
    0
   ],
   "spread": {
    "lo": 1.0,
    "p10": 2.4,
    "q1": 3.8,
    "q3": 8.6,
    "p90": 13.3,
    "hi": 23.1
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 4,
   "aiPplN": null,
   "plainPplN": 3,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.4,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-10",
   "name": "Escalating a stuck load to the account manager",
   "summary": "",
   "domain": "communication",
   "inst": 5,
   "ppl": 4,
   "median": 5.0,
   "hours": 0.4,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-20",
   "cadence": [
    1,
    1,
    1,
    1,
    1,
    0,
    0
   ],
   "spread": {
    "lo": 0.9,
    "p10": 2.2,
    "q1": 3.2,
    "q3": 6.7,
    "p90": 10.3,
    "hi": 18.0
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 5,
   "aiPplN": null,
   "plainPplN": 4,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.4,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-12",
   "name": "Archiving closed claim files",
   "summary": "",
   "domain": "documentation",
   "inst": 2,
   "ppl": 1,
   "median": 13.0,
   "hours": 0.4,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-22",
   "cadence": [
    2,
    0,
    0,
    0,
    0,
    0,
    0
   ],
   "spread": {
    "lo": 2.2,
    "p10": 4.4,
    "q1": 8.3,
    "q3": 22.1,
    "p90": 34.2,
    "hi": 59.7
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 2,
   "aiPplN": null,
   "plainPplN": 1,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.4,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-13",
   "name": "Adjusting a customer's credit hold",
   "summary": "",
   "domain": "finance",
   "inst": 3,
   "ppl": 2,
   "median": 8.0,
   "hours": 0.4,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-23",
   "cadence": [
    -1,
    1,
    1,
    1,
    1,
    0,
    0
   ],
   "spread": {
    "lo": 1.4,
    "p10": 3.2,
    "q1": 5.1,
    "q3": 11.4,
    "p90": 17.7,
    "hi": 30.8
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 3,
   "aiPplN": null,
   "plainPplN": 2,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.4,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-09",
   "name": "Requesting a W-9 from a new vendor",
   "summary": "",
   "domain": "procurement",
   "inst": 2,
   "ppl": 2,
   "median": 8.0,
   "hours": 0.3,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-29",
   "cadence": [
    2,
    0,
    0,
    0,
    0,
    0,
    0
   ],
   "spread": {
    "lo": 1.4,
    "p10": 2.9,
    "q1": 5.1,
    "q3": 12.9,
    "p90": 19.9,
    "hi": 34.8
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 2,
   "aiPplN": null,
   "plainPplN": 2,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.3,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  },
  {
   "id": "tail-14",
   "name": "Booking a hotel for a driver on a stranded load",
   "summary": "",
   "domain": "internal-ops",
   "inst": 1,
   "ppl": 1,
   "median": 19.0,
   "hours": 0.3,
   "ai": 0,
   "hasAi": false,
   "aiPpl": 0,
   "steps": 0,
   "trunked": false,
   "disc": "2026-06-24",
   "cadence": [
    1,
    0,
    0,
    0,
    0,
    0,
    0
   ],
   "spread": {
    "lo": 3.2,
    "p10": 6.8,
    "q1": 12.2,
    "q3": 30.6,
    "p90": 47.3,
    "hi": 82.6
   },
   "apps": [],
   "appMix": [],
   "aiMedMin": null,
   "plainMedMin": null,
   "aiRunN": 0,
   "plainRunN": 1,
   "aiPplN": null,
   "plainPplN": 1,
   "aiToolMedMin": null,
   "aiHours": 0,
   "totalHours": 0.3,
   "phases": [],
   "trunk": null,
   "alignedRuns": 0,
   "coverage": null,
   "branches": [],
   "shapes": [],
   "shapesRemainder": 0,
   "aiSteps": null
  }
 ],
 "ai": {
  "people": 14,
  "devices": 16,
  "tools": [
   {
    "key": "chatgpt",
    "name": "ChatGPT",
    "via": "OpenAI \u00b7 in the browser",
    "people": 11,
    "moments": 1842,
    "hours": 27.4,
    "apps": [
     "Chrome",
     "Edge"
    ],
    "lastSeen": "2026-07-09"
   },
   {
    "key": "copilot",
    "name": "Microsoft Copilot",
    "via": "Built into Microsoft 365",
    "people": 7,
    "moments": 946,
    "hours": 14.8,
    "apps": [
     "Outlook",
     "Excel",
     "Word"
    ],
    "lastSeen": "2026-07-09"
   },
   {
    "key": "claude",
    "name": "Claude",
    "via": "Anthropic \u00b7 in the browser",
    "people": 3,
    "moments": 214,
    "hours": 4.6,
    "apps": [
     "Chrome"
    ],
    "lastSeen": "2026-07-08"
   },
   {
    "key": "gemini",
    "name": "Gemini",
    "via": "Google \u00b7 in the browser",
    "people": 2,
    "moments": 71,
    "hours": 1.3,
    "apps": [
     "Chrome"
    ],
    "lastSeen": "2026-07-01"
   }
  ],
  "categories": [
   {
    "name": "Document drafting & email",
    "pct": 36
   },
   {
    "name": "Lookup & verification",
    "pct": 24
   },
   {
    "name": "Summarizing records",
    "pct": 18
   },
   {
    "name": "Data & spreadsheet work",
    "pct": 14
   },
   {
    "name": "Other",
    "pct": 8
   }
  ],
  "prompts": [
   {
    "provider": "openai",
    "n": 1842,
    "people": 11
   },
   {
    "provider": "microsoft",
    "n": 946,
    "people": 7
   },
   {
    "provider": "anthropic",
    "n": 214,
    "people": 3
   },
   {
    "provider": "google",
    "n": 71,
    "people": 2
   }
  ],
  "daily": [
   {
    "d": "2026-05-12",
    "v": 26
   },
   {
    "d": "2026-05-13",
    "v": 30
   },
   {
    "d": "2026-05-14",
    "v": 27
   },
   {
    "d": "2026-05-15",
    "v": 32
   },
   {
    "d": "2026-05-16",
    "v": 0
   },
   {
    "d": "2026-05-17",
    "v": 0
   },
   {
    "d": "2026-05-18",
    "v": 32
   },
   {
    "d": "2026-05-19",
    "v": 37
   },
   {
    "d": "2026-05-20",
    "v": 42
   },
   {
    "d": "2026-05-21",
    "v": 37
   },
   {
    "d": "2026-05-22",
    "v": 44
   },
   {
    "d": "2026-05-23",
    "v": 0
   },
   {
    "d": "2026-05-24",
    "v": 0
   },
   {
    "d": "2026-05-25",
    "v": 42
   },
   {
    "d": "2026-05-26",
    "v": 48
   },
   {
    "d": "2026-05-27",
    "v": 54
   },
   {
    "d": "2026-05-28",
    "v": 47
   },
   {
    "d": "2026-05-29",
    "v": 55
   },
   {
    "d": "2026-05-30",
    "v": 0
   },
   {
    "d": "2026-05-31",
    "v": 0
   },
   {
    "d": "2026-06-01",
    "v": 51
   },
   {
    "d": "2026-06-02",
    "v": 59
   },
   {
    "d": "2026-06-03",
    "v": 66
   },
   {
    "d": "2026-06-04",
    "v": 57
   },
   {
    "d": "2026-06-05",
    "v": 66
   },
   {
    "d": "2026-06-06",
    "v": 0
   },
   {
    "d": "2026-06-07",
    "v": 0
   },
   {
    "d": "2026-06-08",
    "v": 61
   },
   {
    "d": "2026-06-09",
    "v": 69
   },
   {
    "d": "2026-06-10",
    "v": 77
   },
   {
    "d": "2026-06-11",
    "v": 67
   },
   {
    "d": "2026-06-12",
    "v": 78
   },
   {
    "d": "2026-06-13",
    "v": 0
   },
   {
    "d": "2026-06-14",
    "v": 0
   },
   {
    "d": "2026-06-15",
    "v": 71
   },
   {
    "d": "2026-06-16",
    "v": 80
   },
   {
    "d": "2026-06-17",
    "v": 89
   },
   {
    "d": "2026-06-18",
    "v": 78
   },
   {
    "d": "2026-06-19",
    "v": 89
   },
   {
    "d": "2026-06-20",
    "v": 0
   },
   {
    "d": "2026-06-21",
    "v": 0
   },
   {
    "d": "2026-06-22",
    "v": 81
   },
   {
    "d": "2026-06-23",
    "v": 91
   },
   {
    "d": "2026-06-24",
    "v": 101
   },
   {
    "d": "2026-06-25",
    "v": 88
   },
   {
    "d": "2026-06-26",
    "v": 101
   },
   {
    "d": "2026-06-27",
    "v": 0
   },
   {
    "d": "2026-06-28",
    "v": 0
   },
   {
    "d": "2026-06-29",
    "v": 90
   },
   {
    "d": "2026-06-30",
    "v": 102
   },
   {
    "d": "2026-07-01",
    "v": 113
   },
   {
    "d": "2026-07-02",
    "v": 98
   },
   {
    "d": "2026-07-03",
    "v": 112
   },
   {
    "d": "2026-07-04",
    "v": 0
   },
   {
    "d": "2026-07-05",
    "v": 0
   },
   {
    "d": "2026-07-06",
    "v": 100
   },
   {
    "d": "2026-07-07",
    "v": 113
   },
   {
    "d": "2026-07-08",
    "v": 125
   },
   {
    "d": "2026-07-09",
    "v": 108
   }
  ]
 }
};
